/**
 * frontend/src/components/ChartCommentStrip.tsx
 *
 * Annotation strip that lives below every chart. Visibility per
 * CLAUDE.md Section 14:
 *
 *   Analyst   — strip hidden, but the Sources line still renders
 *               (provenance is presentation-critical in all modes).
 *   Commentary — strip visible, collapsed by default. Click [+] to
 *                expand and reveal Purpose / Key Findings / Narrative.
 *   Present   — strip visible AND auto-expanded for the three
 *                "always-on" charts: cumulative_returns,
 *                stress_test_comparison, significance_journey_matrix.
 *                Others stay collapsed; expanded on demand for Q&A.
 *
 * The narrative content is generated by /api/explain/chart and cached
 * in glossaryStore.charts. The strip fires the request the first time
 * it mounts in Commentary or Present mode; subsequent mounts read from
 * the store. Falling back to a skeleton-loader when the request is in
 * flight avoids the "blank annotation" failure mode.
 */
import { useEffect, useState } from 'react'
import { Plus, Minus, MessageSquare } from 'lucide-react'
import { useUI } from '../context/UIContext'
import { useGlossaryStore } from '../stores/glossaryStore'
import { useProvenanceStore } from '../stores/provenanceStore'
import { useStrategiesStore } from '../stores/strategiesStore'
import {
  CHART_PROVENANCE_REGISTRY,
  formatSource,
} from '../types/provenance'

// Charts that auto-expand in Present mode. These are the three the
// audience needs to see narrated without an extra click during the live
// demo. Other charts stay collapsed so the slide isn't a wall of text.
const PRESENT_AUTO_EXPAND = new Set([
  'cumulative_returns',
  'stress_test_comparison',
  'significance_journey_matrix',
  'correlation_breakdown_chart',
])

interface Props {
  chartId: string
  /** Chart-type hint passed to the Explainer Agent. */
  chartType?: string
  /** The raw data being rendered — sent to /api/explain/chart so the
   *  narrative is anchored to actual values, not a generic description. */
  chartData?: unknown
  /** Visual accent on the strip's left border. Tinted to match the screen
   *  the chart lives on (Statistical Evidence = teal, Regime = purple, …). */
  accentColor?: string
}

export default function ChartCommentStrip({
  chartId,
  chartType = 'unknown',
  chartData,
  accentColor = '#3b82f6',
}: Props) {
  const { mode } = useUI()
  const explanation = useGlossaryStore((s) => s.charts[chartId])
  const inflight = useGlossaryStore((s) => s.inflight.has(`chart:${chartId}`))
  const loadChart = useGlossaryStore((s) => s.loadChart)
  const strategies = useStrategiesStore((s) => s.strategies)
  const provenanceSeries = useProvenanceStore((s) => s.series)

  const [expanded, setExpanded] = useState(() =>
    mode === 'present' && PRESENT_AUTO_EXPAND.has(chartId),
  )

  // Re-evaluate expansion when mode changes. Commentary→Present should
  // auto-expand the highlighted charts; Present→Analyst should collapse.
  useEffect(() => {
    if (mode === 'present' && PRESENT_AUTO_EXPAND.has(chartId)) {
      setExpanded(true)
    } else if (mode === 'analyst') {
      setExpanded(false)
    }
  }, [mode, chartId])

  // Fetch the chart explanation the first time the strip is needed.
  // Skipped in Analyst mode — only the Sources line shows there, which
  // doesn't need the Explainer.
  useEffect(() => {
    if (mode === 'analyst') return
    if (explanation || inflight) return
    // Build a results map keyed by strategy name — the Explainer Agent
    // uses this for grounding callouts in actual numbers.
    const currentResults: Record<string, unknown> = {}
    for (const s of strategies) {
      currentResults[s.strategy_name] = s as unknown as Record<string, unknown>
    }
    void loadChart(chartId, chartType, chartData, currentResults)
  }, [mode, chartId, chartType, chartData, explanation, inflight, strategies, loadChart])

  // ── Sources line — always visible regardless of mode ──────────────────
  const seriesIds = CHART_PROVENANCE_REGISTRY[chartId] ?? []
  const sourcesText = seriesIds
    .map((id) => provenanceSeries[id])
    .filter((s) => s !== undefined)
    .map((s) => `${s.display_name}: ${formatSource(s.source_type, s.source_detail)}`)
    .join('  ·  ')

  const showStripBody = mode !== 'analyst'
  const showSourcesLine = sourcesText.length > 0

  // Nothing to render? Stay silent so charts without provenance and
  // without an explainer entry don't add a vestigial divider.
  if (!showStripBody && !showSourcesLine) return null

  return (
    <div
      className="-mt-1 border-t border-x border-b border-border bg-overlay/40 rounded-b"
      style={{ borderLeftColor: accentColor, borderLeftWidth: 3 }}
      data-testid={`chart-strip-${chartId}`}
    >
      {showStripBody && (
        <button
          type="button"
          onClick={() => setExpanded((v) => !v)}
          className="w-full flex items-center justify-between px-3 py-1.5 text-2xs text-muted hover:text-white transition-colors"
          aria-expanded={expanded}
          aria-label={`${expanded ? 'Collapse' : 'Expand'} commentary for ${chartId}`}
        >
          <span className="flex items-center gap-2">
            <MessageSquare className="w-3 h-3" />
            <span className="uppercase tracking-wide">Purpose</span>
            {explanation?.hover_summary && (
              <span className="text-cbd5e1 normal-case tracking-normal">
                {explanation.hover_summary}
              </span>
            )}
            {!explanation && inflight && (
              <span className="text-muted/60 italic">Analysing chart…</span>
            )}
          </span>
          {expanded ? <Minus className="w-3 h-3" /> : <Plus className="w-3 h-3" />}
        </button>
      )}

      {showStripBody && expanded && (
        <div className="px-3 pb-3 pt-1 space-y-2 text-xs leading-relaxed">
          {explanation?.purpose && (
            <section>
              <div className="text-2xs uppercase tracking-wide text-muted">Purpose</div>
              <p className="text-white">{explanation.purpose}</p>
            </section>
          )}

          {explanation?.key_callouts && explanation.key_callouts.length > 0 && (
            <section>
              <div className="text-2xs uppercase tracking-wide text-muted">Key observations</div>
              <ul className="text-white space-y-0.5 list-disc list-inside">
                {explanation.key_callouts.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            </section>
          )}

          {explanation?.narrative && (
            <section>
              <div className="text-2xs uppercase tracking-wide text-muted">Analyst note</div>
              <p className="text-white">{explanation.narrative}</p>
            </section>
          )}

          {explanation?.what_to_watch && (
            <section>
              <div className="text-2xs uppercase tracking-wide text-muted">What to watch</div>
              <p className="text-white">{explanation.what_to_watch}</p>
            </section>
          )}

          {!explanation && !inflight && (
            <p className="text-muted italic">
              Commentary unavailable — the Explainer Agent did not return a
              narrative for this chart. The Sources line below is still authoritative.
            </p>
          )}
        </div>
      )}

      {showSourcesLine && (
        <div className="px-3 py-1.5 border-t border-border/40">
          <span className="text-2xs uppercase tracking-wide text-muted mr-2">
            Sources
          </span>
          <span className="text-2xs text-cbd5e1 font-normal">
            {sourcesText}
          </span>
        </div>
      )}
    </div>
  )
}
