"""
Sprint 2 remediation — data provenance tests.
Tests that provenance.json is generated correctly and that every source_type
matches the actual data origin as required by CLAUDE.md Section 4b.

The mandatory test test_provenance_matches_actual_source() comes directly
from the CLAUDE.md spec — Sprint 2 does not close until it passes.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "backend"))
os.environ.setdefault("SECRET_KEY", "test-secret-key-at-least-32-characters-long")
os.environ.setdefault("ENVIRONMENT", "test")
os.environ.setdefault("MASTER_API_KEY", "test_master_key")
os.environ.setdefault(
    "ALLOWED_EMAILS",
    "ruurdsm@queens.edu,thaob@queens.edu,murdockm@queens.edu,panttserk@queens.edu",
)

# ── Helpers ────────────────────────────────────────────────────────────────────

def _load_provenance() -> dict:
    """Load the provenance.json generated by the pipeline, if it exists."""
    provenance_path = Path(__file__).parent.parent / "backend" / "data" / "provenance.json"
    if not provenance_path.exists():
        pytest.skip("provenance.json not yet generated — run get_full_history() first")
    return json.loads(provenance_path.read_text(encoding="utf-8"))


def _get_data_series_registry() -> list[dict]:
    """Returns the list of series records from provenance.json."""
    data = _load_provenance()
    return data.get("series", [])


# ── Mandatory CLAUDE.md test ───────────────────────────────────────────────────

def test_provenance_matches_actual_source():
    """
    MANDATORY: from CLAUDE.md Section 4b.
    Sprint 2 does not close until this test passes.

    Verifies:
    - excel_provided series reference the Excel file with a sheet name
    - yfinance series are only for SPY — BND and HYG must not appear
    - fred_api series contain VIXCLS and DGS2 — not DGS10 (DGS10 is in Excel)
    """
    registry = _get_data_series_registry()
    assert len(registry) > 0, "data_series_registry is empty"

    excel_series = [s for s in registry if s["source_type"] == "excel_provided"]
    for series in excel_series:
        detail = series["source_detail"]
        assert detail.get("file") == "FNA_670_Project_Sources.xlsx", (
            f"Series '{series['series_id']}' has wrong file: {detail.get('file')}"
        )
        assert detail.get("sheet") is not None, (
            f"Series '{series['series_id']}' is missing sheet name"
        )
        assert detail["sheet"] != "", (
            f"Series '{series['series_id']}' has empty sheet name"
        )

    yfinance_series = [s for s in registry if s["source_type"] == "yfinance"]
    for series in yfinance_series:
        detail = series["source_detail"]
        ticker = detail.get("ticker", "")
        # SPY is the primary yfinance ticker (equity daily).
        # LQD is the pre-BND IG bridge (2002-07 to 2007-04); it is the only
        # permitted exception to the SPY-only rule because no Excel series covers
        # the 2002-2007 IG gap and LQD tracks the same benchmark family as BND.
        assert ticker in ("SPY", "LQD"), (
            f"yfinance series '{series['series_id']}' has ticker '{ticker}' — "
            "only SPY (equity daily) and LQD (pre-BND IG bridge) are permitted"
        )

    # BND and HYG must NEVER appear as yfinance-sourced series
    yfinance_tickers = [s["source_detail"].get("ticker") for s in yfinance_series]
    assert "BND" not in yfinance_tickers, "BND appears in yfinance series — must come from Excel"
    assert "HYG" not in yfinance_tickers, "HYG appears in yfinance series — must come from Excel"

    fred_series = [s for s in registry if s["source_type"] == "fred_api"]
    fred_ids = [s["source_detail"].get("series_id", "") for s in fred_series]
    assert "VIXCLS" in fred_ids, "VIXCLS must be in fred_api series"
    assert "DGS2" in fred_ids, "DGS2 must be in fred_api series"
    assert "DGS10" not in fred_ids, (
        "DGS10 appears in fred_api series — DGS10 comes from Excel, not FRED"
    )


# ── provenance.json structure tests ───────────────────────────────────────────

def test_provenance_json_has_series_key():
    data = _load_provenance()
    assert "series" in data, "provenance.json missing 'series' key"


def test_provenance_json_has_cross_validation_key():
    data = _load_provenance()
    assert "cross_validation" in data, "provenance.json missing 'cross_validation' key"


def test_provenance_json_series_have_required_fields():
    registry = _get_data_series_registry()
    required = {"series_id", "display_name", "source_type", "source_detail", "frequency", "loaded_at"}
    for s in registry:
        missing = required - set(s.keys())
        assert not missing, f"Series '{s.get('series_id', '?')}' missing fields: {missing}"


def test_provenance_json_source_types_are_valid():
    valid = {"excel_provided", "yfinance", "fred_api", "ken_french", "constant"}
    registry = _get_data_series_registry()
    for s in registry:
        assert s["source_type"] in valid, (
            f"Series '{s['series_id']}' has invalid source_type: '{s['source_type']}'"
        )


def test_provenance_json_frequencies_are_valid():
    valid = {"daily", "monthly", "quarterly"}
    registry = _get_data_series_registry()
    for s in registry:
        assert s["frequency"] in valid, (
            f"Series '{s['series_id']}' has invalid frequency: '{s['frequency']}'"
        )


def test_provenance_json_equity_monthly_is_excel():
    """The authoritative equity series must be marked as excel_provided."""
    registry = _get_data_series_registry()
    equity = next((s for s in registry if s["series_id"] == "equity_monthly"), None)
    if equity is None:
        pytest.skip("equity_monthly not in registry yet — pipeline may not have run")
    assert equity["source_type"] == "excel_provided"


def test_provenance_json_spy_daily_is_yfinance():
    """SPY daily must be marked as yfinance — it is the only yfinance series."""
    registry = _get_data_series_registry()
    spy = next((s for s in registry if s["series_id"] == "equity_daily_spy"), None)
    if spy is None:
        pytest.skip("equity_daily_spy not in registry yet")
    assert spy["source_type"] == "yfinance"
    assert spy["source_detail"]["ticker"] == "SPY"


def test_provenance_json_ig_monthly_is_excel():
    """IG bond returns come from the Excel file — not yfinance BND."""
    registry = _get_data_series_registry()
    ig = next((s for s in registry if s["series_id"] == "ig_monthly_bnd"), None)
    if ig is None:
        pytest.skip("ig_monthly_bnd not in registry yet")
    assert ig["source_type"] == "excel_provided", (
        f"ig_monthly_bnd source_type is '{ig['source_type']}' — must be excel_provided"
    )


def test_provenance_json_vix_is_fred():
    """VIX comes from FRED (VIXCLS) — not Excel."""
    registry = _get_data_series_registry()
    vix = next((s for s in registry if s["series_id"] == "vix_daily"), None)
    if vix is None:
        pytest.skip("vix_daily not in registry yet")
    assert vix["source_type"] == "fred_api"
    assert vix["source_detail"]["series_id"] == "VIXCLS"


# ── API endpoint test ─────────────────────────────────────────────────────────

def test_provenance_api_endpoint_returns_200():
    """GET /api/v1/provenance must return 200 (even with empty series)."""
    from fastapi.testclient import TestClient
    import importlib
    import main as main_module
    importlib.reload(main_module)
    client = TestClient(main_module.app)
    resp = client.get("/api/v1/provenance")
    assert resp.status_code == 200


def test_provenance_api_endpoint_returns_series_key():
    """Response must contain 'series' key."""
    from fastapi.testclient import TestClient
    import importlib
    import main as main_module
    importlib.reload(main_module)
    client = TestClient(main_module.app)
    resp = client.get("/api/v1/provenance")
    data = resp.json()
    assert "series" in data
