"""
tools/academic_docx.py

Assembles the two Word (.docx) deliverables — the midpoint submission
paper and the executive brief — from a data bundle and a set of
pre-generated narrative sections.

These builders are pure document assembly: no LLM calls, no database
reads. The endpoint in main.py gathers the data (tools/academic_export.
gather_document_data) and generates the prose (harness_narrative), then
hands both here. Keeping assembly separate means the page geometry, the
AI DRAFT banner, and the APA table style are defined in exactly one
place.

Formatting follows the FNA 670 brief: 12 pt Times New Roman, double
line spacing, 1-inch margins, page numbers in the footer, and the
mandatory AI DRAFT banner repeated in the header of every page. The
builder is unopinionated about page count — content length plus double
spacing produces the ~3-page midpoint and ~5-page brief naturally.
"""
from __future__ import annotations

import re
from datetime import date, datetime, timezone
from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_COLOR_INDEX, WD_LINE_SPACING
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

# Inline [[VERIFY: …]] markers — the Academic Writer is instructed to wrap
# any uncertain numeric value in one rather than insert it silently.
_VERIFY_RE = re.compile(r"(\[\[VERIFY:.*?\]\])")

from tools.academic_export import (
    table_drawdown, table_factor_loadings, table_regime_conditional,
    table_summary_statistics,
)

_BODY_FONT = "Times New Roman"
_AI_DRAFT_BANNER_TEXT = "AI DRAFT — REQUIRES HUMAN REVIEW"
_AI_DRAFT_SUBTITLE = (
    "First-draft document generated by the Portfolio Intelligence System "
    "from real platform data. Every figure, table and narrative claim must "
    "be verified and refined by a team member before submission."
)


# ── Low-level docx helpers ────────────────────────────────────────────────────

def _set_run_color(run, hex_color: str) -> None:
    rgb = hex_color.lstrip("#")
    run.font.color.rgb = RGBColor(int(rgb[0:2], 16), int(rgb[2:4], 16), int(rgb[4:6], 16))


def _add_page_number(paragraph) -> None:
    """
    Inserts a live PAGE field into a paragraph. python-docx has no API for
    page numbers, so the Word field is built from raw OOXML elements — the
    standard fldChar(begin) / instrText(PAGE) / fldChar(end) sequence.
    """
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = "PAGE"
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.append(begin)
    run._r.append(instr)
    run._r.append(end)


def _new_document() -> Document:
    """
    A Document pre-configured to the FNA 670 formatting brief: 1-inch
    margins, 12 pt Times New Roman double-spaced body, an AI DRAFT banner
    in the page header, and a page number centred in the footer.
    """
    doc = Document()

    section = doc.sections[0]
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)

    # Body text — Times New Roman 12 pt, double-spaced.
    normal = doc.styles["Normal"]
    normal.font.name = _BODY_FONT
    normal.font.size = Pt(12)
    normal.paragraph_format.line_spacing_rule = WD_LINE_SPACING.DOUBLE
    normal.paragraph_format.space_after = Pt(0)

    # AI DRAFT banner — repeated in the header so it appears on every page.
    header_para = section.header.paragraphs[0]
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    head_run = header_para.add_run(_AI_DRAFT_BANNER_TEXT)
    head_run.bold = True
    head_run.font.name = _BODY_FONT
    head_run.font.size = Pt(10)
    _set_run_color(head_run, "#b45309")

    # Page number — centred in the footer.
    footer_para = section.footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _add_page_number(footer_para)

    return doc


def _add_title_lines(doc: Document, lines: list[str], *, big_first: bool = False) -> None:
    """Centred title block — the first line optionally rendered large."""
    for i, line in enumerate(lines):
        para = doc.add_paragraph()
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
        run = para.add_run(line)
        run.font.name = _BODY_FONT
        run.bold = i == 0
        run.font.size = Pt(20 if (big_first and i == 0) else 12)


def _add_heading(doc: Document, text: str, *, size: int = 13) -> None:
    """A bold Times New Roman heading — kept on the body font, not Word's
    Heading styles, so the 12 pt Times New Roman brief holds throughout."""
    para = doc.add_paragraph()
    para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    para.paragraph_format.space_before = Pt(12)
    para.paragraph_format.space_after = Pt(4)
    run = para.add_run(text)
    run.bold = True
    run.font.name = _BODY_FONT
    run.font.size = Pt(size)


def _add_body(doc: Document, text: str) -> None:
    """
    Renders blank-line-separated prose — one Word paragraph per block.
    Any [[VERIFY: …]] marker the Academic Writer emitted for an uncertain
    value is rendered bold with a yellow highlight, so it is unmissable
    to whoever refines the draft rather than a silently-trusted figure.
    """
    for block in (text or "").strip().split("\n\n"):
        block = block.strip()
        if not block:
            continue
        para = doc.add_paragraph()
        for part in _VERIFY_RE.split(block):
            if not part:
                continue
            run = para.add_run(part)
            run.font.name = _BODY_FONT
            run.font.size = Pt(12)
            if _VERIFY_RE.fullmatch(part):
                run.bold = True
                run.font.highlight_color = WD_COLOR_INDEX.YELLOW


def _shade_cell(cell, hex_color: str) -> None:
    """Sets a table cell's background fill via OOXML w:shd."""
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color.lstrip("#"))
    cell._tc.get_or_add_tcPr().append(shd)


def _add_callout(doc: Document, title: str, body_lines: list[str]) -> None:
    """
    A boxed, amber-shaded callout — a single-cell bordered table — for
    the human-input prompts a team member must act on. Bold throughout
    so it survives scanning and is the first thing the reader sees.
    """
    table = doc.add_table(rows=1, cols=1)
    table.style = "Table Grid"          # a visible 1 pt border on all sides
    cell = table.rows[0].cells[0]
    _shade_cell(cell, "#fef3c7")        # light amber

    title_para = cell.paragraphs[0]
    title_para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    title_para.paragraph_format.space_after = Pt(4)
    t = title_para.add_run(f"✏️  {title}")
    t.bold = True
    t.font.name = _BODY_FONT
    t.font.size = Pt(11)
    _set_run_color(t, "#92400e")        # dark amber

    for line in body_lines:
        para = cell.add_paragraph()
        para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
        para.paragraph_format.space_after = Pt(2)
        run = para.add_run(line)
        run.bold = True
        run.font.name = _BODY_FONT
        run.font.size = Pt(10)
        _set_run_color(run, "#1f2937")
    # Breathing room below the box.
    doc.add_paragraph().paragraph_format.space_after = Pt(2)


# Human-input callouts for the midpoint paper — Bob must act on these
# before the document is submitted; the AI cannot write them authentically.
# The Roles callout sits BELOW its pre-seeded draft — the draft is a
# factual scaffold from real platform activity, not the final text.
_ROLES_CALLOUT_TITLE = "BOB — PERSONALISE THIS SECTION"
_ROLES_CALLOUT_LINES = [
    "The draft above is pre-seeded with your actual platform activity "
    "data. It is factually accurate but written in AI language.",
    "",
    "Your task:",
    "1.  Confirm the numbers are correct",
    "2.  Add specific examples of your analytical contributions — what "
    "did you personally interpret, question, or discover?",
    "3.  Rewrite in your own voice",
    "4.  Add anything the platform data does not capture — literature "
    "review, offline analysis, team discussions",
]
_NEXT_STEPS_CALLOUT_TITLE = "BOB — REVIEW AND REFINE"
_NEXT_STEPS_CALLOUT_LINES = [
    "The draft below lists known analytical limitations and planned "
    "enhancements. Edit it to reflect YOUR analytical priorities — not "
    "just the engineering roadmap.",
    "",
    "Ask yourself: what would YOU investigate next given the findings? "
    "That is what belongs here.",
]


def _add_table(doc: Document, caption: str, headers: list[str],
               rows: list[list[str]]) -> None:
    """
    Inserts a captioned APA-style table. Empty data is rendered as a
    single [DATA PENDING] line rather than an empty grid, so the gap is
    visible to whoever refines the draft.
    """
    cap = doc.add_paragraph()
    cap.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    cap.paragraph_format.space_before = Pt(8)
    cap_run = cap.add_run(caption)
    cap_run.bold = True
    cap_run.italic = True
    cap_run.font.name = _BODY_FONT
    cap_run.font.size = Pt(11)

    if not rows:
        pending = doc.add_paragraph("[DATA PENDING] — table data unavailable.")
        pending.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
        return

    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    for i, label in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = label
        for para in cell.paragraphs:
            para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
            for run in para.runs:
                run.bold = True
                run.font.name = _BODY_FONT
                run.font.size = Pt(10)
    for row in rows:
        cells = table.add_row().cells
        for i, value in enumerate(row):
            cells[i].text = str(value)
            for para in cells[i].paragraphs:
                # Tables stay single-spaced inside the double-spaced body.
                para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
                for run in para.runs:
                    run.font.name = _BODY_FONT
                    run.font.size = Pt(10)


def _timestamp_line(doc: Document) -> None:
    """A small grey generated-on line, single-spaced."""
    para = doc.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    run = para.add_run(
        f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    run.italic = True
    run.font.name = _BODY_FONT
    run.font.size = Pt(9)
    _set_run_color(run, "#64748b")


def _ai_draft_notice(doc: Document) -> None:
    """An in-body restatement of the AI DRAFT warning, below the title."""
    para = doc.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    para.paragraph_format.space_after = Pt(8)
    run = para.add_run(_AI_DRAFT_SUBTITLE)
    run.italic = True
    run.font.name = _BODY_FONT
    run.font.size = Pt(9)
    _set_run_color(run, "#b45309")


# ── Deliverable builders ──────────────────────────────────────────────────────

def build_midpoint_paper(data: dict[str, Any], narratives: dict[str, str]) -> bytes:
    """
    The three-page midpoint submission. Four sections per the FNA 670
    brief: Data & Methodology, Preliminary Results (with the summary-
    statistics and regime-conditional tables embedded), Roles & Division
    of Labor, and Next Steps & Open Questions.
    """
    doc = _new_document()

    period = data.get("study_period", {})
    _add_title_lines(doc, [
        "Portfolio Intelligence System — Midpoint Submission",
        "FNA 670 — Summer 2026",
        "McColl School of Business",
        date.today().strftime("%B %d, %Y"),
    ])
    _ai_draft_notice(doc)
    _timestamp_line(doc)

    _add_heading(doc, "1. Data and Methodology")
    _add_body(doc, narratives.get("methodology", "[DATA PENDING]"))

    _add_heading(doc, "2. Preliminary Results")
    _add_body(doc, narratives.get("results", "[DATA PENDING]"))
    h, r = table_summary_statistics(data.get("summary_statistics", []))
    _add_table(doc, "Table 1. Summary Statistics by Asset Class", h, r)
    h, r = table_regime_conditional(data.get("regime_conditional", []))
    _add_table(doc, "Table 2. Regime-Conditional Performance "
                     "(Pre- vs Post-2022)", h, r)

    # Section 3 is pre-seeded from real Team Activity counts — a factual
    # draft — with a "BOB — PERSONALISE" callout beneath directing him to
    # rewrite it in his own voice and add what the platform cannot show.
    _add_heading(doc, "3. Roles and Division of Labor")
    _add_body(doc, narratives.get("roles", "[DATA PENDING]"))
    _add_callout(doc, _ROLES_CALLOUT_TITLE, _ROLES_CALLOUT_LINES)

    # Section 4 keeps the AI draft, but a callout above it directs Bob to
    # refine it into his own analytical priorities.
    _add_heading(doc, "4. Next Steps and Open Questions")
    _add_callout(doc, _NEXT_STEPS_CALLOUT_TITLE, _NEXT_STEPS_CALLOUT_LINES)
    _add_body(doc, narratives.get("next_steps", "[DATA PENDING]"))

    period_note = doc.add_paragraph()
    period_note.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    note_run = period_note.add_run(
        f"Study period: {period.get('start', '—')} to "
        f"{period.get('end', '—')} ({period.get('n_months', 0)} monthly "
        "observations). Benchmark: 100% S&P 500. Factor model: Carhart "
        "four-factor (MKT-RF, SMB, HML, MOM).")
    note_run.italic = True
    note_run.font.name = _BODY_FONT
    note_run.font.size = Pt(9)
    _set_run_color(note_run, "#64748b")

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def build_executive_brief(data: dict[str, Any], narratives: dict[str, str]) -> bytes:
    """
    The five-page executive brief for a senior investment audience. A
    title page, then Executive Summary, Methodology Overview, four Key
    Findings (with the regime-conditional, summary-statistics and factor-
    loadings tables embedded), Limitations and Risks, and Final
    Recommendations.
    """
    doc = _new_document()

    # ── Title page ────────────────────────────────────────────────────────
    for _ in range(3):
        doc.add_paragraph()
    _add_title_lines(doc, [
        "Asset Allocation Strategies and Risk-Adjusted Performance",
    ], big_first=True)
    doc.add_paragraph()
    _add_title_lines(doc, [
        "Executive Brief",
        "FNA 670 — Summer 2026",
        "Forest Capital / McColl School of Business",
        date.today().strftime("%B %d, %Y"),
    ])
    _ai_draft_notice(doc)
    _timestamp_line(doc)
    doc.add_page_break()

    _add_heading(doc, "Executive Summary")
    _add_body(doc, narratives.get("exec_summary", "[DATA PENDING]"))

    _add_heading(doc, "Methodology Overview")
    _add_body(doc, narratives.get("methodology", "[DATA PENDING]"))

    _add_heading(doc, "Key Findings and Insights")

    _add_heading(doc, "Finding 1: The 2022 Correlation Break", size=12)
    _add_body(doc, narratives.get("finding_1", "[DATA PENDING]"))
    h, r = table_regime_conditional(data.get("regime_conditional", []))
    _add_table(doc, "Table 1. Regime-Conditional Performance "
                     "(Pre- vs Post-2022)", h, r)

    _add_heading(doc, "Finding 2: Static Allocation Results", size=12)
    _add_body(doc, narratives.get("finding_2", "[DATA PENDING]"))
    h, r = table_summary_statistics(data.get("summary_statistics", []))
    _add_table(doc, "Table 2. Summary Statistics by Asset Class", h, r)

    _add_heading(doc, "Finding 3: Dynamic Allocation Results", size=12)
    _add_body(doc, narratives.get("finding_3", "[DATA PENDING]"))
    h, r = table_drawdown(data.get("drawdown_comparison", []))
    _add_table(doc, "Table 3. Drawdown and Recovery by Strategy", h, r)

    _add_heading(doc, "Finding 4: Factor Analysis", size=12)
    _add_body(doc, narratives.get("finding_4", "[DATA PENDING]"))
    h, r = table_factor_loadings(data.get("factor_loadings", []))
    _add_table(doc, "Table 4. Carhart Four-Factor Loadings "
                     "(* significant at p < .05)", h, r)

    _add_heading(doc, "Limitations and Risks")
    _add_body(doc, narratives.get("limitations", "[DATA PENDING]"))

    _add_heading(doc, "Final Recommendations")
    _add_body(doc, narratives.get("recommendations", "[DATA PENDING]"))

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
