"""
tools/academic_docx.py

Assembles the executive brief Word (.docx) deliverable from a data
bundle and a set of pre-generated narrative sections. (PR-B June 2026
retired build_midpoint_paper alongside the midpoint endpoint.)

These builders are pure document assembly: no LLM calls, no database
reads. The endpoint in main.py gathers the data (tools/academic_export.
gather_document_data) and generates the prose (harness_narrative), then
hands both here. Keeping assembly separate means the page geometry, the
AI DRAFT banner, and the APA table style are defined in exactly one
place.

Formatting follows the FNA 670 brief: 12 pt Times New Roman, double
line spacing, 1-inch margins, page numbers in the footer, and the
mandatory AI DRAFT banner repeated in the header of every page. The
builder is unopinionated about page count — content length plus double
spacing produces the ~5-page brief naturally.
"""
from __future__ import annotations

import re
from datetime import date, datetime, timezone
from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_COLOR_INDEX, WD_LINE_SPACING
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

# Inline [[VERIFY …]] markers — the Academic Writer wraps any uncertain
# numeric value in [[VERIFY: …]] and every citation in
# [[VERIFY CITATION: …]] rather than inserting it silently. The pattern
# matches both forms so each is rendered as an unmissable working aid.
_VERIFY_RE = re.compile(r"(\[\[VERIFY.*?\]\])")

from tools.academic_export import (
    table_bootstrap_ci, table_cost_sensitivity, table_crisis_performance,
    table_drawdown, table_factor_loadings, table_invariant_summary,
    table_regime_conditional, table_statistical_tests,
    table_strategy_performance_full, table_summary_statistics,
)

_BODY_FONT = "Times New Roman"
_AI_DRAFT_BANNER_TEXT = "AI DRAFT — REQUIRES HUMAN REVIEW"
_AI_DRAFT_SUBTITLE = (
    "First-draft document generated by the Portfolio Intelligence System "
    "from real platform data. Every figure, table and narrative claim must "
    "be verified and refined by a team member before submission."
)


# ── Low-level docx helpers ────────────────────────────────────────────────────

def _set_run_color(run, hex_color: str) -> None:
    rgb = hex_color.lstrip("#")
    run.font.color.rgb = RGBColor(int(rgb[0:2], 16), int(rgb[2:4], 16), int(rgb[4:6], 16))


def _add_page_number(paragraph) -> None:
    """
    Inserts a live PAGE field into a paragraph. python-docx has no API for
    page numbers, so the Word field is built from raw OOXML elements — the
    standard fldChar(begin) / instrText(PAGE) / fldChar(end) sequence.
    """
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = "PAGE"
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.append(begin)
    run._r.append(instr)
    run._r.append(end)


def _new_document() -> Document:
    """
    A Document pre-configured to the FNA 670 formatting brief: 1-inch
    margins, 12 pt Times New Roman double-spaced body, an AI DRAFT banner
    in the page header, and a page number centred in the footer.
    """
    doc = Document()

    section = doc.sections[0]
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)

    # Body text — Times New Roman 12 pt, double-spaced.
    normal = doc.styles["Normal"]
    normal.font.name = _BODY_FONT
    normal.font.size = Pt(12)
    normal.paragraph_format.line_spacing_rule = WD_LINE_SPACING.DOUBLE
    normal.paragraph_format.space_after = Pt(0)

    # AI DRAFT banner — repeated in the header so it appears on every page.
    header_para = section.header.paragraphs[0]
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    head_run = header_para.add_run(_AI_DRAFT_BANNER_TEXT)
    head_run.bold = True
    head_run.font.name = _BODY_FONT
    head_run.font.size = Pt(10)
    _set_run_color(head_run, "#b45309")

    # Page number — centred in the footer.
    footer_para = section.footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _add_page_number(footer_para)

    return doc


def _add_title_lines(doc: Document, lines: list[str], *, big_first: bool = False) -> None:
    """Centred title block — the first line optionally rendered large."""
    for i, line in enumerate(lines):
        para = doc.add_paragraph()
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
        run = para.add_run(line)
        run.font.name = _BODY_FONT
        run.bold = i == 0
        run.font.size = Pt(20 if (big_first and i == 0) else 12)


def _add_heading(doc: Document, text: str, *, size: int = 13) -> None:
    """A bold Times New Roman heading — kept on the body font, not Word's
    Heading styles, so the 12 pt Times New Roman brief holds throughout."""
    para = doc.add_paragraph()
    para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    para.paragraph_format.space_before = Pt(12)
    para.paragraph_format.space_after = Pt(4)
    run = para.add_run(text)
    run.bold = True
    run.font.name = _BODY_FONT
    run.font.size = Pt(size)


def _add_body(doc: Document, text: str) -> None:
    """
    Renders blank-line-separated prose — one Word paragraph per block.
    Any [[VERIFY: …]] marker the Academic Writer emitted for an uncertain
    value is rendered bold with a yellow highlight, so it is unmissable
    to whoever refines the draft rather than a silently-trusted figure.
    """
    for block in (text or "").strip().split("\n\n"):
        block = block.strip()
        if not block:
            continue
        para = doc.add_paragraph()
        for part in _VERIFY_RE.split(block):
            if not part:
                continue
            run = para.add_run(part)
            run.font.name = _BODY_FONT
            run.font.size = Pt(12)
            if _VERIFY_RE.fullmatch(part):
                run.bold = True
                run.font.highlight_color = WD_COLOR_INDEX.YELLOW


def _shade_cell(cell, hex_color: str) -> None:
    """Sets a table cell's background fill via OOXML w:shd."""
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color.lstrip("#"))
    cell._tc.get_or_add_tcPr().append(shd)


def _add_callout(doc: Document, title: str, body_lines: list[str]) -> None:
    """
    A boxed, amber-shaded callout — a single-cell bordered table — for
    the human-input prompts a team member must act on. Bold throughout
    so it survives scanning and is the first thing the reader sees.
    """
    table = doc.add_table(rows=1, cols=1)
    table.style = "Table Grid"          # a visible 1 pt border on all sides
    cell = table.rows[0].cells[0]
    _shade_cell(cell, "#fef3c7")        # light amber

    title_para = cell.paragraphs[0]
    title_para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    title_para.paragraph_format.space_after = Pt(4)
    t = title_para.add_run(f"✏️  {title}")
    t.bold = True
    t.font.name = _BODY_FONT
    t.font.size = Pt(11)
    _set_run_color(t, "#92400e")        # dark amber

    for line in body_lines:
        para = cell.add_paragraph()
        para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
        para.paragraph_format.space_after = Pt(2)
        run = para.add_run(line)
        run.bold = True
        run.font.name = _BODY_FONT
        run.font.size = Pt(10)
        _set_run_color(run, "#1f2937")
    # Breathing room below the box.
    doc.add_paragraph().paragraph_format.space_after = Pt(2)


# [[BOB]] placeholder callouts removed (May 26 2026 — submission night).
# The rubric requires analytical interpretation to be PRESENT, not
# human-authored. Six callouts ("BOB — PERSONALISE THIS SECTION", "BOB
# — REVIEW AND REFINE", "BOB — YOUR INTERPRETATION REQUIRED", "BOB —
# YOUR FRAMING", "BOB — YOUR JUDGEMENT", "BOB — YOUR RECOMMENDATION")
# previously sat below their corresponding section bodies. They have
# been removed from the renderer — the Academic Writer's section
# prose now stands as the deliverable's interpretation. Bob edits the
# generated output for voice; he does not write from scratch.
#
# The [[MOLLY]] callouts on the presentation deck are unaffected (see
# academic_deck.py) — they remain because the deck speaker-notes flow
# is structurally different. The submission checklist below has been
# updated to drop the [[BOB]] reference accordingly.

# CAVEAT 1 — the review-required warning box, rendered immediately below
# the AI DRAFT banner on every generated document.
_REVIEW_WARNING_TITLE = "AI DRAFT — REVIEW REQUIRED"
_REVIEW_WARNING_LINES = [
    "This document was generated by AI from platform data. Before "
    "submission:",
    "",
    "CITATIONS: Verify every cited paper exists and says exactly what is "
    "claimed. Do not submit unverified citations — check author, year, "
    "title, and the specific finding cited.",
    "STATISTICS: Confirm every number against the platform Analytics "
    "page. If a value differs from what you see on screen, the screen "
    "wins.",
    "YOUR VOICE: This draft uses AI language. Rewrite it in your own "
    "words before submitting — faculty will recognise AI prose if it is "
    "left unedited.",
    "HALLUCINATIONS: AI can generate plausible-sounding but incorrect "
    "claims. Read every sentence critically.",
]

# CAVEAT 5 — the submission checklist, rendered at the end of every
# generated document. The final submitted file should carry none of
# these working aids.
_SUBMISSION_CHECKLIST_LINES = [
    "Before submitting this document:",
    "□  All citations verified against original sources",
    "□  All statistics confirmed against the platform Analytics page",
    "□  All [[VERIFY]] markers resolved and removed",
    "□  All [[MOLLY]] callouts addressed and removed",
    "□  Document rewritten in your own voice throughout",
    "□  AI DRAFT banner removed from the final submission version",
    "□  Academic Review run against the final draft",
]


def _add_review_warning_box(doc: Document) -> None:
    """CAVEAT 1 — the boxed review-required warning, below the banner."""
    _add_callout(doc, _REVIEW_WARNING_TITLE, _REVIEW_WARNING_LINES)


def _add_submission_checklist(doc: Document) -> None:
    """CAVEAT 5 — the end-of-document submission checklist."""
    _add_heading(doc, "Submission Checklist")
    for line in _SUBMISSION_CHECKLIST_LINES:
        para = doc.add_paragraph()
        para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
        para.paragraph_format.space_after = Pt(2)
        run = para.add_run(line)
        run.font.name = _BODY_FONT
        run.font.size = Pt(10)
        _set_run_color(run, "#92400e")


def _add_table(doc: Document, caption: str, headers: list[str],
               rows: list[list[str]]) -> None:
    """
    Inserts a captioned APA-style table. Empty data is rendered as a
    single [DATA PENDING] line rather than an empty grid, so the gap is
    visible to whoever refines the draft.
    """
    cap = doc.add_paragraph()
    cap.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    cap.paragraph_format.space_before = Pt(8)
    cap_run = cap.add_run(caption)
    cap_run.bold = True
    cap_run.italic = True
    cap_run.font.name = _BODY_FONT
    cap_run.font.size = Pt(11)

    if not rows:
        pending = doc.add_paragraph("[DATA PENDING] — table data unavailable.")
        pending.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
        return

    table = doc.add_table(rows=1, cols=len(headers))
    table.style = "Light Grid Accent 1"
    for i, label in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = label
        for para in cell.paragraphs:
            para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
            for run in para.runs:
                run.bold = True
                run.font.name = _BODY_FONT
                run.font.size = Pt(10)
    for row in rows:
        cells = table.add_row().cells
        for i, value in enumerate(row):
            cells[i].text = str(value)
            for para in cells[i].paragraphs:
                # Tables stay single-spaced inside the double-spaced body.
                para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
                for run in para.runs:
                    run.font.name = _BODY_FONT
                    run.font.size = Pt(10)


def _timestamp_line(doc: Document) -> None:
    """A small grey generated-on line, single-spaced."""
    para = doc.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    run = para.add_run(
        f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    run.italic = True
    run.font.name = _BODY_FONT
    run.font.size = Pt(9)
    _set_run_color(run, "#64748b")


def _ai_draft_notice(doc: Document) -> None:
    """An in-body restatement of the AI DRAFT warning, below the title."""
    para = doc.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.SINGLE
    para.paragraph_format.space_after = Pt(8)
    run = para.add_run(_AI_DRAFT_SUBTITLE)
    run.italic = True
    run.font.name = _BODY_FONT
    run.font.size = Pt(9)
    _set_run_color(run, "#b45309")


# ── Deliverable builders ──────────────────────────────────────────────────────

def _add_audit_disclosure_appendix(
    doc: Document, disclosures: dict[str, Any] | None,
) -> None:
    """
    Workstream D — appends the Audit Disclosure Appendix to a report.
    Renders three blocks deterministically (no AI):

      - Headline paragraph naming the two audit runs and their verdicts.
      - Acknowledged statistical warnings table (Layer · Check ·
        Reviewed by · Reviewed at · Note).
      - Intentional methodology overrides table (Check · Category ·
        Marked by · Marked at · Note).

    `disclosures` is the gather_audit_disclosures() output; None is
    treated as "no audit on record" and the appendix renders a single
    explanatory paragraph in place of the tables. This keeps the
    appendix structurally complete even when the audit subsystem has
    no history.
    """
    from tools.audit_summary import (
        acknowledged_statistical_rows, intentional_methodology_rows,
    )

    _add_heading(doc, "Audit Disclosure Appendix")

    if not disclosures or not disclosures.get("available"):
        _add_body(doc, (
            "No platform audit was on record at the time of generation. "
            "The team should run the platform's statistical audit and "
            "methodology review before submission so this appendix "
            "carries the audit verdict and any reviewed warnings. The "
            "report-readiness gate is fail-open in this state — a future "
            "draft generated against a populated audit history will "
            "carry the full disclosure record here."
        ))
        return

    stat = disclosures.get("statistical") or {}
    meth = disclosures.get("methodology") or {}

    stat_line = ""
    if stat.get("present"):
        stat_line = (
            f"Statistical audit (run #{stat.get('run_id')}, completed "
            f"{stat.get('completed_at') or '—'}): "
            f"{int(stat.get('total') or 0)} checks · "
            f"{int(stat.get('passed') or 0)} passed · "
            f"{int(stat.get('warnings') or 0)} warnings · "
            f"{int(stat.get('failures') or 0)} failures."
        )
    meth_line = ""
    if meth.get("present"):
        verdict = meth.get("verdict") or "—"
        meth_line = (
            f"Methodology review ({verdict}, run "
            f"{meth.get('run_at') or '—'}): "
            f"{int(meth.get('total') or 0)} checks · "
            f"{int(meth.get('passed') or 0)} passed · "
            f"{int(meth.get('warnings') or 0)} warnings · "
            f"{int(meth.get('failures') or 0)} failures."
        )
    headline_parts = [
        "This appendix records the disclosure rationale for every "
        "audit warning the team reviewed prior to generating this "
        "report. The platform refused to generate the document while "
        "any warning was unreviewed, so the records below represent the "
        "team's complete response to the audit findings on file.",
    ]
    if stat_line:
        headline_parts.append(stat_line)
    if meth_line:
        headline_parts.append(meth_line)
    _add_body(doc, "\n\n".join(headline_parts))

    # ── Statistical disclosures ───────────────────────────────────────
    stat_rows = acknowledged_statistical_rows(disclosures)
    _add_heading(doc, "Statistical Audit — Acknowledged Warnings", size=12)
    if not stat_rows:
        _add_body(doc, (
            "The statistical audit surfaced no warnings requiring "
            "acknowledgement in this run."))
    else:
        _add_table(
            doc, "Table A1. Acknowledged statistical warnings.",
            ["Layer", "Check", "Reviewed by", "Reviewed at", "Note"],
            stat_rows,
        )

    # ── Methodology disclosures ───────────────────────────────────────
    meth_rows = intentional_methodology_rows(disclosures)
    _add_heading(doc, "Methodology Review — Intentional Disclosures",
                 size=12)
    if not meth_rows:
        _add_body(doc, (
            "No methodology checks were marked as intentional in this "
            "run."))
    else:
        _add_table(
            doc, "Table A2. Methodology checks marked intentional.",
            ["Check", "Category", "Marked by", "Marked at", "Note"],
            meth_rows,
        )


def build_executive_brief(data: dict[str, Any], narratives: dict[str, str]) -> bytes:
    """
    The executive brief for a senior investment audience.

    Rewritten June 18 2026 to the FNA 670 rubric's six required sections,
    in rubric order. Earlier (June 6) the brief led with "The Answer"
    and embedded a "Five Human Decisions" section + a "Part II preview";
    review against the rubric flagged the latter two as non-rubric
    content and the section ordering as out-of-spec. Visuals are
    referenced by name in the prose (per rubric §6) and supported by
    the embedded table set; the platform's matplotlib chart surfaces
    (cumulative return, implied asset allocation, efficient frontier)
    are pointed to as live companion artifacts.

      1. Executive Summary    -- verdict + headline figures
      2. Methodology Overview -- HMM + OOS window + validation layers
      3. Key Findings         -- three-strategy comparison + honest 2-of-9
      4. Limitations & Risks  -- four mandatory limitations, no future-work
      5. Final Recommendations -- investment conclusions from the OOS
         Sharpe + diversification evidence; cached-regime fallback so the
         section is data-independent and never renders empty
      6. Visuals              -- captioned interpretations of the platform's
         chart surfaces so reviewers can navigate to each one
    """
    doc = _new_document()

    # ── Title page ────────────────────────────────────────────────────────
    for _ in range(3):
        doc.add_paragraph()
    _add_title_lines(doc, [
        "Asset Allocation Strategies and Risk-Adjusted Performance",
    ], big_first=True)
    doc.add_paragraph()
    _add_title_lines(doc, [
        "Executive Brief",
        "FNA 670 -- Summer 2026",
        "Forest Capital / McColl School of Business",
        date.today().strftime("%B %d, %Y"),
    ])
    _ai_draft_notice(doc)
    _timestamp_line(doc)
    _add_review_warning_box(doc)
    doc.add_page_break()

    # Section 1 -- EXECUTIVE SUMMARY. Opens with the verdict + the
    # headline numbers a senior investment reader expects on page 1.
    # Drawdown comparison table embedded here so the 27-point number
    # is visible alongside the prose claim.
    _add_heading(doc, "1. Executive Summary")
    _add_body(doc, narratives.get("executive_summary", "[DATA PENDING]"))
    h, r = table_drawdown(data.get("drawdown_comparison", []))
    _add_table(doc, "Table 1. Drawdown and Recovery by Strategy", h, r)

    # Section 2 -- METHODOLOGY OVERVIEW. Moved from §3 to §2 to match
    # the rubric ordering (methodology sets the stage before findings).
    # Factor-loading table accompanies the validation prose.
    _add_heading(doc, "2. Methodology Overview")
    _add_body(doc, narratives.get("methodology", "[DATA PENDING]"))
    h, r = table_factor_loadings(data.get("factor_loadings", []))
    _add_table(doc, "Table 2. Carhart Four-Factor Loadings "
                    "(* significant at p < .05)", h, r)

    # Section 3 -- KEY FINDINGS AND INSIGHTS. The three-strategy
    # comparison + honest 2-of-9 + FDR disclosure. Two tables anchor
    # the findings (summary statistics + regime-conditional performance).
    _add_heading(doc, "3. Key Findings and Insights")
    _add_body(doc, narratives.get("key_findings", "[DATA PENDING]"))
    # Audit-readiness one-liner -- surfaces the platform's audit
    # verdict here (the validation context for the findings claims).
    from tools.audit_summary import audit_summary_sentence
    audit_line = audit_summary_sentence(data.get("audit_disclosures") or {})
    if audit_line:
        _add_body(doc, audit_line)
    h, r = table_summary_statistics(data.get("summary_statistics", []))
    _add_table(doc, "Table 3. Summary Statistics by Asset Class", h, r)
    h, r = table_regime_conditional(data.get("regime_conditional", []))
    _add_table(doc, "Table 4. Regime-Conditional Performance "
                    "(Pre- vs Post-2022)", h, r)

    # Section 4 -- LIMITATIONS AND RISKS. The four mandatory limitations
    # only -- the previous "Part II preview" content was dropped (it
    # was non-rubric "next steps" content the panel feedback explicitly
    # called out as "putting out next steps rather than final
    # recommendations"). Audit body paragraph anchors the validation
    # surface as the closing limitation context.
    _add_heading(doc, "4. Limitations and Risks")
    _add_body(doc, narratives.get("limitations", "[DATA PENDING]"))
    from tools.audit_summary import audit_body_paragraph
    audit_para = audit_body_paragraph(data.get("audit_disclosures") or {})
    if audit_para:
        _add_body(doc, audit_para)

    # Section 5 -- FINAL RECOMMENDATIONS. Reframed as INVESTMENT
    # CONCLUSIONS drawn from the OOS evidence, not a point-in-time
    # portfolio position. The cached-regime fallback (assembled in
    # gather_document_data -> _gather_live_recommendation) means the
    # section can ALWAYS state the recommendation: live data when
    # available, cached regime when the live build is degraded, with
    # the staleness explicitly disclosed in the prose.
    _add_heading(doc, "5. Final Recommendations")
    _add_body(doc, narratives.get(
        "final_recommendations", "[DATA PENDING]"))

    # Section 6 -- VISUALS. A captioned roster of the platform's chart
    # surfaces with a one-paragraph interpretation each. Reviewers can
    # navigate to each artifact on the live platform; the tables above
    # carry the static visual content the rubric expects to find in
    # the document body.
    _add_heading(doc, "6. Visuals to Demonstrate the Insights")
    _add_body(doc, narratives.get("visuals", "[DATA PENDING]"))

    # Audit Disclosure Appendix carries the platform's audit trail.
    _add_audit_disclosure_appendix(doc, data.get("audit_disclosures"))

    _add_submission_checklist(doc)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── Editor-content export ─────────────────────────────────────────────────────

def _tiptap_text(node: Any) -> str:
    """The concatenated plain text of a TipTap node and its descendants."""
    if not isinstance(node, dict):
        return ""
    if node.get("text"):
        return str(node["text"])
    return "".join(_tiptap_text(c) for c in (node.get("content") or []))


def build_editor_docx(
    draft: dict[str, Any],
    appendix_data: dict[str, Any] | None = None,
) -> bytes:
    """
    Renders an editor draft (a midpoint_paper, executive_brief, or
    analytical_appendix) to a .docx straight from its TipTap
    content_json — the document exactly as the author has edited it in
    the in-platform editor.

    Unlike build_midpoint_paper / build_executive_brief, this does not
    regenerate narrative: it is a faithful export of the current editor
    content. The AI DRAFT banner and submission checklist are still
    applied; any [[VERIFY]] markers left in the text are rendered
    highlighted by _add_body.

    Analytical-appendix special case (the appendix is table-heavy by
    design): when document_type == "analytical_appendix" and
    appendix_data is supplied, the eight evidence tables (A1-H1) are
    re-injected after the prose nodes so the in-editor export carries
    the full evidentiary record. The data is the same dict produced by
    tools.academic_export.gather_analytical_appendix_data() and the
    table builders are the same ones used by build_analytical_appendix
    — no recomputation, no LLM calls. The caller is responsible for
    fetching appendix_data on the async edge; this builder stays sync.
    """
    doc = _new_document()
    _add_title_lines(doc, [
        draft.get("title", "Document"),
        "FNA 670 — Summer 2026",
        "McColl School of Business",
        date.today().strftime("%B %d, %Y"),
    ])
    _ai_draft_notice(doc)
    _timestamp_line(doc)
    _add_review_warning_box(doc)

    content = draft.get("content_json") or {}
    nodes = content.get("content", []) if isinstance(content, dict) else []
    for node in nodes:
        if not isinstance(node, dict):
            continue
        ntype = node.get("type")
        if ntype == "heading":
            text = _tiptap_text(node).strip()
            if text:
                level = (node.get("attrs") or {}).get("level", 1)
                _add_heading(doc, text, size=13 if level <= 1 else 12)
        elif ntype == "paragraph":
            text = _tiptap_text(node).strip()
            if text:
                _add_body(doc, text)
        elif ntype in ("bulletList", "orderedList"):
            for item in (node.get("content") or []):
                text = _tiptap_text(item).strip()
                if text:
                    _add_body(doc, f"•  {text}")

    # An empty draft still produces a structurally valid document.
    if not nodes:
        _add_body(doc, (draft.get("content_text")
                        or "[DATA PENDING] — the draft is empty.").strip())

    # Analytical Appendix: re-inject the eight evidence tables after the
    # author's prose so the in-editor export carries the full record.
    if (draft.get("document_type") == "analytical_appendix"
            and appendix_data is not None):
        _add_appendix_tables(doc, appendix_data)

    _add_submission_checklist(doc)
    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _add_appendix_tables(
    doc: Document, data: dict[str, Any],
) -> None:
    """Append the eight evidence tables (A1-H1) to the document. Shared
    between build_analytical_appendix (full regenerated path) and the
    in-editor export of an analytical_appendix draft, so the tables
    appear identically in both surfaces. Pure assembly — no DB reads,
    no LLM calls."""
    _add_heading(doc, "Evidence Tables")

    h, r = table_summary_statistics(data.get("summary_statistics", []))
    _add_table(doc, "Table A1. Summary Statistics by Asset Class", h, r)

    h, r = table_strategy_performance_full(
        data.get("strategy_results") or {})
    _add_table(doc, "Table B1. Full-Period Performance by Strategy "
                    "(sorted by Sharpe)", h, r)

    h, r = table_statistical_tests(data.get("strategy_results") or {})
    _add_table(doc, "Table C1. Statistical Tests by Strategy "
                    "(paired-t, FDR-corrected, DSR, PSR, SPA)", h, r)

    h, r = table_bootstrap_ci(data.get("bootstrap_ci_sharpe") or [])
    _add_table(doc, "Table D1. Sharpe Ratio with 95% Bootstrap CI "
                    "(block bootstrap, length 12, 10,000 resamples)", h, r)

    h, r = table_factor_loadings(data.get("factor_loadings", []))
    _add_table(doc, "Table E1. Carhart Four-Factor Loadings by Strategy "
                    "(* significant at p < .05)", h, r)

    h, r = table_crisis_performance(data.get("crisis_performance"))
    _add_table(doc, "Table F1. Cumulative Return by Strategy and "
                    "Crisis Window", h, r)

    h, r = table_cost_sensitivity(data.get("cost_sensitivity"))
    _add_table(doc, "Table G1. Net-of-Cost Sharpe at 10/15/20 bps "
                    "per Material Rebalance (OOS Window)", h, r)

    h, r = table_invariant_summary(data.get("invariant_summary"))
    _add_table(doc, "Table H1. Latest Warm Invariant Verdict "
                    "(deterministic detection only — see "
                    "docs/INVARIANTS.md)", h, r)


# ── Analytical Appendix (June 2 2026) ─────────────────────────────────────────

# The Analytical Appendix is the project's evidentiary record — the data
# that backs every claim in the executive brief and the panel
# presentation. It is intentionally table-heavy and rhetorically minimal:
# each section opens with a short Academic Writer-generated paragraph
# explaining what the data shows, then the data itself in an APA-style
# table. The eight sections (A through H) map one-to-one to the eight
# cache reads in tools.academic_export.gather_analytical_appendix_data.
#
# Pure assembly — no LLM calls or database reads inside this function.
# The endpoint in main.py gathers the data and generates the narratives,
# then hands both to build_analytical_appendix.


_APPENDIX_SECTION_TITLES = [
    "A. Data and Methodology",
    "B. Full Strategy Performance",
    "C. Statistical Tests",
    "D. Bootstrap Confidence Intervals",
    "E. Factor Loadings",
    "F. Crisis Window Performance",
    "G. Transaction Cost Sensitivity",
    "H. Validation Audit Summary",
]


def _appendix_section_keys() -> list[str]:
    """The narratives dict key for each appendix section. One key per
    section letter — the endpoint generates one paragraph per key,
    and the builder renders it under the matching heading."""
    return ["appendix_a", "appendix_b", "appendix_c", "appendix_d",
            "appendix_e", "appendix_f", "appendix_g", "appendix_h"]


def _add_reproducibility_line(doc: Document, data_hash: str | None) -> None:
    """The footer line carrying the data hash + generation timestamp.

    The hash anchors every figure in the appendix to a specific
    strategy_results_cache row. A reader investigating a number can
    look the row up by hash and reconstruct the analytics on top of
    it. Renders at the END of the appendix body (above the submission
    checklist) so the trailing structure is: tables → reproducibility
    line → audit disclosure → checklist."""
    _add_heading(doc, "Reproducibility")
    hash_display = (data_hash if data_hash else "[DATA PENDING]")
    body = (
        f"Data hash: {hash_display}\n"
        f"Generated at: "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
        "Every figure in this appendix traces to the strategy_results_cache "
        "row identified by the hash above. The same hash on the analytics "
        "metric rows confirms the bootstrap CIs, factor loadings, crisis "
        "performance, and transaction-cost sensitivity were computed from "
        "the same underlying data as the strategy table."
    )
    _add_body(doc, body)


def build_analytical_appendix(
    data: dict[str, Any], narratives: dict[str, str],
) -> bytes:
    """
    The Analytical Appendix — the evidentiary record behind every
    claim in the executive brief and the panel presentation. Eight
    sections, each opening with a short Academic Writer paragraph
    then the data in an APA-style table:

      A. Data and Methodology          — study_period + summary_statistics
      B. Full Strategy Performance     — strategy_results_cache
      C. Statistical Tests             — strategy_results_cache (p-values)
      D. Bootstrap Confidence Intervals — academic_analytics metric
      E. Factor Loadings               — academic_analytics metric (Carhart)
      F. Crisis Window Performance     — crisis_performance metric
      G. Transaction Cost Sensitivity  — oos_cost_sensitivity metric
      H. Validation Audit Summary      — invariant_summary metric +
                                         audit_disclosures bundle

    Trailing structure: Reproducibility line (data_hash + timestamp),
    Audit Disclosure Appendix (statistical audit + methodology QA +
    intentional overrides — the same renderer the brief uses), and
    the standard Submission Checklist.

    Pure assembly. No LLM calls. No database reads.
    """
    doc = _new_document()

    # ── Title page ────────────────────────────────────────────────────────
    for _ in range(3):
        doc.add_paragraph()
    _add_title_lines(doc, [
        "Asset Allocation Strategies and Risk-Adjusted Performance",
    ], big_first=True)
    doc.add_paragraph()
    _add_title_lines(doc, [
        "Analytical Appendix",
        "FNA 670 — Summer 2026",
        "Forest Capital / McColl School of Business",
        date.today().strftime("%B %d, %Y"),
    ])
    _ai_draft_notice(doc)
    _timestamp_line(doc)
    _add_review_warning_box(doc)
    doc.add_page_break()

    # ── Section A — Data and Methodology ──────────────────────────────────
    _add_heading(doc, _APPENDIX_SECTION_TITLES[0])
    _add_body(doc, narratives.get("appendix_a", "[DATA PENDING]"))
    h, r = table_summary_statistics(data.get("summary_statistics", []))
    _add_table(doc, "Table A1. Summary Statistics by Asset Class", h, r)

    # ── Section B — Full Strategy Performance ─────────────────────────────
    _add_heading(doc, _APPENDIX_SECTION_TITLES[1])
    _add_body(doc, narratives.get("appendix_b", "[DATA PENDING]"))
    h, r = table_strategy_performance_full(
        data.get("strategy_results") or {})
    _add_table(doc, "Table B1. Full-Period Performance by Strategy "
                    "(sorted by Sharpe)", h, r)

    # ── Section C — Statistical Tests ─────────────────────────────────────
    _add_heading(doc, _APPENDIX_SECTION_TITLES[2])
    _add_body(doc, narratives.get("appendix_c", "[DATA PENDING]"))
    h, r = table_statistical_tests(data.get("strategy_results") or {})
    _add_table(doc, "Table C1. Statistical Tests by Strategy "
                    "(paired-t, FDR-corrected, DSR, PSR, SPA)", h, r)

    # ── Section D — Bootstrap Confidence Intervals ────────────────────────
    _add_heading(doc, _APPENDIX_SECTION_TITLES[3])
    _add_body(doc, narratives.get("appendix_d", "[DATA PENDING]"))
    h, r = table_bootstrap_ci(data.get("bootstrap_ci_sharpe") or [])
    _add_table(doc, "Table D1. Sharpe Ratio with 95% Bootstrap CI "
                    "(block bootstrap, length 12, 10,000 resamples)", h, r)

    # ── Section E — Factor Loadings ───────────────────────────────────────
    _add_heading(doc, _APPENDIX_SECTION_TITLES[4])
    _add_body(doc, narratives.get("appendix_e", "[DATA PENDING]"))
    h, r = table_factor_loadings(data.get("factor_loadings", []))
    _add_table(doc, "Table E1. Carhart Four-Factor Loadings by Strategy "
                    "(* significant at p < .05)", h, r)

    # ── Section F — Crisis Window Performance ─────────────────────────────
    _add_heading(doc, _APPENDIX_SECTION_TITLES[5])
    _add_body(doc, narratives.get("appendix_f", "[DATA PENDING]"))
    h, r = table_crisis_performance(data.get("crisis_performance"))
    _add_table(doc, "Table F1. Cumulative Return by Strategy and "
                    "Crisis Window († indicates partial-overlap)", h, r)

    # ── Section G — Transaction Cost Sensitivity ──────────────────────────
    _add_heading(doc, _APPENDIX_SECTION_TITLES[6])
    _add_body(doc, narratives.get("appendix_g", "[DATA PENDING]"))
    h, r = table_cost_sensitivity(data.get("cost_sensitivity"))
    _add_table(doc, "Table G1. Net-of-Cost Sharpe at 10/15/20 bps "
                    "per Material Rebalance (OOS Window)", h, r)

    # ── Section H — Validation Audit Summary ──────────────────────────────
    _add_heading(doc, _APPENDIX_SECTION_TITLES[7])
    _add_body(doc, narratives.get("appendix_h", "[DATA PENDING]"))
    h, r = table_invariant_summary(data.get("invariant_summary"))
    _add_table(doc, "Table H1. Latest Warm Invariant Verdict "
                    "(deterministic detection only — see "
                    "docs/INVARIANTS.md)", h, r)

    # ── Reproducibility footer line ───────────────────────────────────────
    _add_reproducibility_line(doc, data.get("data_hash"))

    # ── Audit Disclosure Appendix (reuses the brief renderer) ─────────────
    _add_audit_disclosure_appendix(doc, data.get("audit_disclosures"))

    _add_submission_checklist(doc)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
