"""tools/cio_recommendation.py — the live CIO recommendation, cached by
data_hash.

The deliberate counterpart to tools/play_by_play.py. Play-by-play is an
immutable historical record keyed by event_id, written once and never
recomputed. This is a LIVE signal: it reflects the CURRENT regime state
and the CURRENT live blend weights, which move every month as new market
data lands. So it caches by DATA_HASH, not by a stable key, and the two
surfaces deliberately do not share cache logic.

The four-component council recommendation (signal / confidence /
dissenting_view / limitations, PR #209) is generated by a single LLM
call that fires ONCE per data_hash, written to cio_recommendations, and
served from the DB on every read until the next data_hash change. The
recompute is fired by the same hash-change pipeline that warms the
analytics cache (cache_warm_state._default_warm_fn), never manually.

Fail-open throughout: a missing strategy cache, a failed HMM fit, or an
unavailable LLM each degrade to a documented fallback. When the LLM is
unavailable the deterministic four-component object is built from the
regime and the blend so a recommendation always exists; the mandatory
limitations are always present regardless.
"""
from __future__ import annotations

import structlog

from agents.recommendation_prompts import (
    LANDING_PAGE_RECOMMENDATION_SYSTEM_PROMPT,
    MANDATORY_LIMITATIONS,
)

log = structlog.get_logger(__name__)

_DB_AVAILABLE = False
try:  # pragma: no cover - environment dependent
    from database import AsyncSessionLocal
    _DB_AVAILABLE = AsyncSessionLocal is not None
except Exception:  # noqa: BLE001
    AsyncSessionLocal = None  # type: ignore[assignment]

_DETERMINISTIC = "deterministic_fallback"


# ── context assembly (pure; testable with synthetic inputs) ──────────────────


def compute_context(
    strategy_results: dict,
    hmm_result: dict,
    current: dict,
) -> dict:
    """Assemble the live decision context from the current regime read,
    the regime blends, and the live probability-weighted blend. Pure
    given its inputs (no DB, no LLM, no HMM fit), so it is the unit-
    tested core. Returns {regime, posterior, blend_weights, ess,
    ess_warning, names} or {"error": ...}."""
    from tools.regime_meta_optimizer import (
        compute_regime_blends, probability_weighted_blend,
    )

    posterior = (current or {}).get("hmm_probabilities") or {}
    regime = (current or {}).get("hmm_regime")
    built = compute_regime_blends(strategy_results, hmm_result)
    if built.get("error"):
        return {"error": built["error"]}

    names = built["names"]
    blend_weights = probability_weighted_blend(built["blends"], posterior)
    ess = built["effective_n"].get(regime) if regime else None
    floor = 2.0 * len(names)
    ess_warning = bool(ess is not None and ess < floor)
    prob = None
    if regime and isinstance(posterior, dict):
        try:
            prob = float(posterior.get(regime))
        except (TypeError, ValueError):
            prob = None

    return {
        "regime": regime,
        "posterior": {k: round(float(v), 4)
                      for k, v in posterior.items()
                      if v is not None},
        "probability": prob,
        "blend_weights": blend_weights,
        "ess": ess,
        "ess_warning": ess_warning,
        "names": names,
    }


# ── four-component recommendation (LLM, fail-open) ───────────────────────────


def _deterministic_recommendation(context: dict) -> dict:
    """A structured four-component recommendation built without the LLM,
    from the regime and the live blend. The fail-open path: it is always
    valid and always carries the four mandatory limitations."""
    regime = context.get("regime") or "uncertain"
    prob = context.get("probability")
    ess = context.get("ess")
    bw = context.get("blend_weights") or {}
    tops = [n for n, _ in sorted(bw.items(), key=lambda kv: kv[1],
                                 reverse=True) if bw.get(n, 0.0) > 0.05][:3]
    tops_str = ", ".join(tops) if tops else "a diversified blend"
    signal = (f"The regime reads {regime}"
              f"{f' (P={prob:.0%})' if isinstance(prob, float) else ''}, "
              f"and the regime-conditional allocation tilts toward "
              f"{tops_str}.")
    dissent = (
        "The allocation depends on the regime read being correct; an HMM "
        "misclassification at a turning point would not be corrected until "
        "next month's data, and the bond sleeve assumes the post-2022 "
        "equity-bond correlation does not invert further.")
    return {
        "signal": signal,
        "confidence": {
            "regime": regime,
            "probability": round(prob, 4) if isinstance(prob, float) else None,
            "ess": round(float(ess), 2) if ess is not None else None,
            "ess_warning": bool(context.get("ess_warning")),
        },
        "dissenting_view": dissent,
        "limitations": list(MANDATORY_LIMITATIONS),
        "_model": _DETERMINISTIC,
    }


def generate_recommendation(context: dict, macro_context: str = "") -> dict:
    """The four-component CIO recommendation. A single LLM call in the
    landing-page framing (PR #209 prompt), grounded in the current
    regime, the live blend, and the current macro context. Fail-open: any
    LLM error returns the deterministic structured recommendation so a
    valid four-component object always results, with the four mandatory
    limitations enforced either way."""
    if context.get("error"):
        return {"error": context["error"]}
    try:
        from agents.base import SONNET_MODEL, call_claude
    except Exception:  # noqa: BLE001
        return _deterministic_recommendation(context)

    bw = context.get("blend_weights") or {}
    tops = sorted(bw.items(), key=lambda kv: kv[1], reverse=True)[:5]
    user = (
        "Current regime: "
        f"{context.get('regime')} (posterior {context.get('posterior')}, "
        f"Kish ESS {context.get('ess')}, ess_warning "
        f"{context.get('ess_warning')}).\n"
        f"Live regime-conditional blend (top weights): {tops}.\n"
        f"{macro_context or ''}\n"
        "Produce the current four-component recommendation as the strict "
        "JSON object specified. Quantify the signal from the regime and "
        "weights, set ess_warning per the value above, and include the "
        "four mandatory limitations verbatim.")
    try:
        import json
        raw = call_claude(SONNET_MODEL,
                          LANDING_PAGE_RECOMMENDATION_SYSTEM_PROMPT, user,
                          max_tokens=600, trigger="cio_recommendation")
        text = (raw or "").strip()
        if text.startswith("```"):
            text = text.strip("`")
        data = json.loads(text[text.find("{"): text.rfind("}") + 1])
        # The four mandatory limitations are non-negotiable: enforce them
        # even if the model omitted or altered one.
        data["limitations"] = list(MANDATORY_LIMITATIONS)
        if not (data.get("signal") and data.get("dissenting_view")
                and isinstance(data.get("confidence"), dict)):
            raise ValueError("incomplete recommendation JSON")
        data["_model"] = SONNET_MODEL
        return data
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_llm_failed", error=str(exc))
        return _deterministic_recommendation(context)


# ── persistence: data_hash cache (serve-from-DB, recompute on change) ────────


async def _current_data_hash() -> str:
    try:
        from tools.audit_assembler import current_data_hash
        return await current_data_hash()
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_hash_error", error=str(exc))
        return ""


async def get_cached_for_hash(data_hash: str) -> dict | None:
    """The cached recommendation for an exact data_hash, or None. The
    cache-hit check: a read whose current hash matches a stored row is
    served from it without recomputing."""
    if not _DB_AVAILABLE or not data_hash:
        return None
    try:
        from sqlalchemy import text
        async with AsyncSessionLocal() as session:  # type: ignore[union-attr]
            row = await session.execute(
                text("SELECT raw_json, data_hash, computed_at "
                     "FROM cio_recommendations WHERE data_hash = :h "
                     "ORDER BY computed_at DESC LIMIT 1"),
                {"h": data_hash})
            r = row.fetchone()
            if not r:
                return None
            payload = dict(r[0]) if r[0] else {}
            payload["data_hash"] = r[1]
            payload["computed_at"] = str(r[2])
            return payload
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_cache_read_error", error=str(exc))
        return None


async def get_latest_recommendation() -> dict | None:
    """The most recent recommendation regardless of hash. The read path
    behind the landing page: serve whatever the hash pipeline last
    computed. Fail-open to None."""
    if not _DB_AVAILABLE:
        return None
    try:
        from sqlalchemy import text
        async with AsyncSessionLocal() as session:  # type: ignore[union-attr]
            row = await session.execute(
                text("SELECT raw_json, data_hash, regime, model, "
                     "computed_at FROM cio_recommendations "
                     "ORDER BY computed_at DESC LIMIT 1"))
            r = row.fetchone()
            if not r:
                return None
            payload = dict(r[0]) if r[0] else {}
            payload["data_hash"] = r[1]
            payload["regime"] = r[2]
            payload["model"] = r[3]
            payload["computed_at"] = str(r[4])
            return payload
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_latest_read_error", error=str(exc))
        return None


async def _persist(data_hash: str, rec: dict, regime: str | None) -> None:
    if not _DB_AVAILABLE or not data_hash:
        return
    import json

    from sqlalchemy import text
    try:
        async with AsyncSessionLocal() as session:  # type: ignore[union-attr]
            await session.execute(
                text(
                    "INSERT INTO cio_recommendations "
                    "(data_hash, signal, confidence, dissenting_view, "
                    " limitations, regime, model, raw_json) "
                    "VALUES (:h, :sig, CAST(:conf AS JSONB), :dis, "
                    " CAST(:lim AS JSONB), :reg, :model, "
                    " CAST(:raw AS JSONB)) "
                    "ON CONFLICT (data_hash) DO NOTHING"),
                {
                    "h": data_hash,
                    "sig": rec.get("signal"),
                    "conf": json.dumps(rec.get("confidence")),
                    "dis": rec.get("dissenting_view"),
                    "lim": json.dumps(rec.get("limitations")),
                    "reg": regime,
                    "model": rec.get("_model"),
                    "raw": json.dumps(rec),
                })
            await session.commit()
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_persist_error", error=str(exc))


async def _build_live_context() -> dict:
    """Render-side: assemble compute_context inputs from the live data —
    the strategy cache, a fresh HMM fit on the equity series, and the
    current regime read. Fail-open to {"error": ...}."""
    try:
        import pandas as pd
        from tools.cache import get_latest_strategy_cache, get_monthly_returns
        from tools.regime_detector import (
            detect_current_regime, fit_hmm_historical,
        )
    except Exception as exc:  # noqa: BLE001
        return {"error": f"imports_unavailable: {exc}"}

    strategy_results = await get_latest_strategy_cache()
    if not strategy_results:
        return {"error": "strategy_results_cache_empty"}
    monthly = await get_monthly_returns()
    if not monthly or not monthly.get("equity") or not monthly.get("dates"):
        return {"error": "monthly_equity_unavailable"}
    idx = pd.to_datetime(monthly["dates"])
    equity = pd.Series(monthly["equity"], index=idx).sort_index()
    hmm_result = fit_hmm_historical(equity)
    if not hmm_result or hmm_result.get("error"):
        return {"error": f"hmm_fit_failed: {(hmm_result or {}).get('error')}"}
    current = detect_current_regime()
    ctx = compute_context(strategy_results, hmm_result, current)
    if ctx.get("error"):
        return ctx
    macro = ""
    try:
        from tools.macro_context import get_macro_context
        macro = get_macro_context() or ""
    except Exception:  # noqa: BLE001
        macro = ""
    return {"context": ctx, "macro": macro}


async def refresh_cio_recommendation(*, force: bool = False) -> dict:
    """The hash-pipeline entry point. Serve the cached recommendation
    when the current data_hash already has one; otherwise build the live
    context, fire the single LLM call, persist under the data_hash, and
    return it. force=True recomputes even on a cache hit (not used by the
    pipeline; available for an operator backfill). Fail-open."""
    data_hash = await _current_data_hash()
    if not force:
        cached = await get_cached_for_hash(data_hash)
        if cached:
            cached["cache"] = "hit"
            return cached

    built = await _build_live_context()
    if built.get("error"):
        log.warning("cio_recommendation_context_unavailable",
                    error=built["error"])
        return built
    rec = generate_recommendation(built["context"], built["macro"])
    if rec.get("error"):
        return rec
    await _persist(data_hash, rec, built["context"].get("regime"))
    rec["cache"] = "miss"
    rec["data_hash"] = data_hash
    log.info("cio_recommendation_computed",
             data_hash=data_hash[:8] if data_hash else "",
             model=rec.get("_model"))
    return rec
