"""tools/cio_recommendation.py — the live CIO recommendation, cached by
data_hash.

The deliberate counterpart to tools/play_by_play.py. Play-by-play is an
immutable historical record keyed by event_id, written once and never
recomputed. This is a LIVE signal: it reflects the CURRENT regime state
and the CURRENT live blend weights, which move every month as new market
data lands. So it caches by DATA_HASH, not by a stable key, and the two
surfaces deliberately do not share cache logic.

The four-component council recommendation (signal / confidence /
dissenting_view / limitations, PR #209) is generated by a single LLM
call that fires ONCE per data_hash, written to cio_recommendations, and
served from the DB on every read until the next data_hash change. The
recompute is fired by the same hash-change pipeline that warms the
analytics cache (cache_warm_state._default_warm_fn), never manually.

Fail-open throughout: a missing strategy cache, a failed HMM fit, or an
unavailable LLM each degrade to a documented fallback. When the LLM is
unavailable the deterministic four-component object is built from the
regime and the blend so a recommendation always exists; the mandatory
limitations are always present regardless.
"""
from __future__ import annotations

import structlog

from agents.recommendation_prompts import (
    LANDING_PAGE_RECOMMENDATION_SYSTEM_PROMPT,
    MANDATORY_LIMITATIONS,
)

log = structlog.get_logger(__name__)

_DB_AVAILABLE = False
try:  # pragma: no cover - environment dependent
    from database import AsyncSessionLocal
    _DB_AVAILABLE = AsyncSessionLocal is not None
except Exception:  # noqa: BLE001
    AsyncSessionLocal = None  # type: ignore[assignment]

_DETERMINISTIC = "deterministic_fallback"


# ── context assembly (pure; testable with synthetic inputs) ──────────────────


def compute_context(
    strategy_results: dict,
    hmm_result: dict,
    current: dict,
) -> dict:
    """Assemble the live decision context from the current regime read,
    the regime blends, and the live probability-weighted blend. Pure
    given its inputs (no DB, no LLM, no HMM fit), so it is the unit-
    tested core. Returns {regime, posterior, blend_weights, ess,
    ess_warning, names} or {"error": ...}."""
    from tools.regime_meta_optimizer import (
        compute_regime_blends, probability_weighted_blend,
    )

    posterior = (current or {}).get("hmm_probabilities") or {}
    regime = (current or {}).get("hmm_regime")
    # PR #282 added monthly_hmm_regime + hmm_models_agree to
    # detect_current_regime(). Thread them through compute_context so
    # the recommendation prose generator and downstream agent context
    # builders all reference the same structured fields rather than
    # digging into the raw `current` dict.
    monthly_regime = (current or {}).get("monthly_hmm_regime")
    hmm_models_agree = (current or {}).get("hmm_models_agree", True)
    built = compute_regime_blends(strategy_results, hmm_result)
    if built.get("error"):
        return {"error": built["error"]}

    names = built["names"]
    blend_weights = probability_weighted_blend(built["blends"], posterior)
    ess = built["effective_n"].get(regime) if regime else None
    floor = 2.0 * len(names)
    ess_warning = bool(ess is not None and ess < floor)
    prob = None
    if regime and isinstance(posterior, dict):
        try:
            prob = float(posterior.get(regime))
        except (TypeError, ValueError):
            prob = None

    return {
        "regime": regime,
        "monthly_regime": monthly_regime,
        "hmm_models_agree": hmm_models_agree,
        "posterior": {k: round(float(v), 4)
                      for k, v in posterior.items()
                      if v is not None},
        "probability": prob,
        "blend_weights": blend_weights,
        "ess": ess,
        "ess_warning": ess_warning,
        "names": names,
    }


# ── four-component recommendation (LLM, fail-open) ───────────────────────────


def _deterministic_recommendation(context: dict) -> dict:
    """A structured four-component recommendation built without the LLM,
    from the regime and the live blend. The fail-open path: it is always
    valid and always carries the four mandatory limitations."""
    regime = context.get("regime") or "uncertain"
    prob = context.get("probability")
    ess = context.get("ess")
    bw = context.get("blend_weights") or {}
    tops = [n for n, _ in sorted(bw.items(), key=lambda kv: kv[1],
                                 reverse=True) if bw.get(n, 0.0) > 0.05][:3]
    tops_str = ", ".join(tops) if tops else "a diversified blend"
    signal = (f"The regime reads {regime}"
              f"{f' (P={prob:.0%})' if isinstance(prob, float) else ''}, "
              f"and the regime-conditional allocation tilts toward "
              f"{tops_str}.")
    recommendation = (
        f"Hold the regime-conditional blend for the {regime} state, "
        f"weighted toward {tops_str}, and rebalance as the regime read "
        f"updates with next month's data.")
    dissent = (
        "The allocation depends on the regime read being correct; an HMM "
        "misclassification at a turning point would not be corrected until "
        "next month's data, and the bond sleeve assumes the post-2022 "
        "equity-bond correlation does not invert further.")
    key_risk = (
        "A sharp regime reversal between monthly reads: the blend would "
        "stay positioned for the prior regime for up to a month, the same "
        "lag that cost the council on the April 2025 tariff reversal.")
    return {
        "signal": signal,
        "recommendation": recommendation,
        "confidence": {
            "regime": regime,
            "probability": round(prob, 4) if isinstance(prob, float) else None,
            "ess": round(float(ess), 2) if ess is not None else None,
            "ess_warning": bool(context.get("ess_warning")),
        },
        "dissenting_view": dissent,
        "key_risk": key_risk,
        "limitations": list(MANDATORY_LIMITATIONS),
        "_model": _DETERMINISTIC,
    }


def generate_recommendation(context: dict, macro_context: str = "") -> dict:
    """The four-component CIO recommendation. A single LLM call in the
    landing-page framing (PR #209 prompt), grounded in the current
    regime, the live blend, and the current macro context. Fail-open: any
    LLM error returns the deterministic structured recommendation so a
    valid four-component object always results, with the four mandatory
    limitations enforced either way."""
    if context.get("error"):
        return {"error": context["error"]}
    try:
        from agents.base import SONNET_MODEL, call_claude
    except Exception:  # noqa: BLE001
        return _deterministic_recommendation(context)

    bw = context.get("blend_weights") or {}
    tops = sorted(bw.items(), key=lambda kv: kv[1], reverse=True)[:5]
    user = (
        "Current regime: "
        f"{context.get('regime')} (posterior {context.get('posterior')}, "
        f"Kish ESS {context.get('ess')}, ess_warning "
        f"{context.get('ess_warning')}).\n"
        f"Live regime-conditional blend (top weights): {tops}.\n"
        f"{macro_context or ''}\n"
        "Produce the current four-component recommendation as the strict "
        "JSON object specified. Quantify the signal from the regime and "
        "weights, set ess_warning per the value above, and include the "
        "four mandatory limitations verbatim.")
    try:
        import json
        raw = call_claude(SONNET_MODEL,
                          LANDING_PAGE_RECOMMENDATION_SYSTEM_PROMPT, user,
                          max_tokens=600, trigger="cio_recommendation")
        text = (raw or "").strip()
        if text.startswith("```"):
            text = text.strip("`")
        data = json.loads(text[text.find("{"): text.rfind("}") + 1])
        # The four mandatory limitations are non-negotiable: enforce them
        # even if the model omitted or altered one.
        data["limitations"] = list(MANDATORY_LIMITATIONS)
        if not (data.get("signal") and data.get("dissenting_view")
                and isinstance(data.get("confidence"), dict)):
            raise ValueError("incomplete recommendation JSON")
        # recommendation and key_risk are required by the card. If the
        # model omitted either, backfill from the deterministic version so
        # the card always has every field rather than failing the whole
        # call over a missing line.
        if not data.get("recommendation") or not data.get("key_risk"):
            fallback = _deterministic_recommendation(context)
            data.setdefault("recommendation", fallback["recommendation"])
            data.setdefault("key_risk", fallback["key_risk"])
            if not data.get("recommendation"):
                data["recommendation"] = fallback["recommendation"]
            if not data.get("key_risk"):
                data["key_risk"] = fallback["key_risk"]
        data["_model"] = SONNET_MODEL
        return data
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_llm_failed", error=str(exc))
        return _deterministic_recommendation(context)


# ── persistence: data_hash cache (serve-from-DB, recompute on change) ────────


async def _current_data_hash() -> str:
    try:
        from tools.audit_assembler import current_data_hash
        return await current_data_hash()
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_hash_error", error=str(exc))
        return ""


async def get_cached_for_hash(data_hash: str) -> dict | None:
    """The cached recommendation for an exact data_hash, or None. The
    cache-hit check: a read whose current hash matches a stored row is
    served from it without recomputing."""
    if not _DB_AVAILABLE or not data_hash:
        return None
    try:
        from sqlalchemy import text
        async with AsyncSessionLocal() as session:  # type: ignore[union-attr]
            row = await session.execute(
                text("SELECT raw_json, data_hash, computed_at "
                     "FROM cio_recommendations WHERE data_hash = :h "
                     "ORDER BY computed_at DESC LIMIT 1"),
                {"h": data_hash})
            r = row.fetchone()
            if not r:
                return None
            payload = dict(r[0]) if r[0] else {}
            payload["data_hash"] = r[1]
            payload["computed_at"] = str(r[2])
            return payload
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_cache_read_error", error=str(exc))
        return None


async def get_latest_recommendation() -> dict | None:
    """The most recent recommendation regardless of hash. The read path
    behind the landing page: serve whatever the hash pipeline last
    computed. Fail-open to None."""
    if not _DB_AVAILABLE:
        return None
    try:
        from sqlalchemy import text
        async with AsyncSessionLocal() as session:  # type: ignore[union-attr]
            row = await session.execute(
                text("SELECT raw_json, data_hash, regime, model, "
                     "computed_at FROM cio_recommendations "
                     "ORDER BY computed_at DESC LIMIT 1"))
            r = row.fetchone()
            if not r:
                return None
            payload = dict(r[0]) if r[0] else {}
            payload["data_hash"] = r[1]
            payload["regime"] = r[2]
            payload["model"] = r[3]
            payload["computed_at"] = str(r[4])
            return payload
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_latest_read_error", error=str(exc))
        return None


async def get_prior_recommendation(current_data_hash: str) -> dict | None:
    """The most recent recommendation written under a DIFFERENT data_hash
    than the current one — i.e. the previous distinct council output the
    pipeline produced before today's data state.

    Used by the CIO's _synthesise step to enable Section C (the "shift
    narrative") of the mandatory transparency structure. When a prior
    exists, the synthesis prompt receives it as `prior_recommendation`
    in the DATA block and the CIO compares prior vs current — what
    regime signal shifted, how the blend moved, what the weight change
    means. When NONE exists (first run after a cache clear, or genuinely
    first ever) the helper returns None and Section C is correctly
    omitted from the response per the system prompt's `CONDITIONAL`
    instruction.

    The data_hash column carries either a bare base hash (older rows)
    or a composite `{base}_{regime}_{bucket}` (newer rows — see the
    comment block above near _composite_key). For the "prior" lookup
    we want any row whose key differs from the current key — that
    captures both a base-hash change (the underlying data moved) AND a
    regime/confidence-bucket change without a base shift. Both count
    as a prior distinct recommendation for narrative purposes.

    Fail-open to None on a DB error, a missing table, or a missing
    current_data_hash. June 5 2026."""
    if not _DB_AVAILABLE or not current_data_hash:
        return None
    try:
        from sqlalchemy import text
        async with AsyncSessionLocal() as session:  # type: ignore[union-attr]
            row = await session.execute(
                text("SELECT raw_json, data_hash, regime, model, "
                     "computed_at FROM cio_recommendations "
                     "WHERE data_hash != :h "
                     "ORDER BY computed_at DESC LIMIT 1"),
                {"h": current_data_hash})
            r = row.fetchone()
            if not r:
                return None
            payload = dict(r[0]) if r[0] else {}
            payload["data_hash"] = r[1]
            payload["regime"] = r[2]
            payload["model"] = r[3]
            payload["computed_at"] = str(r[4])
            return payload
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_prior_read_error", error=str(exc))
        return None


# ── regime-aware cache key (recommendation prose) ──────────────────────────
#
# The narrative prose (signal / recommendation / dissenting view) is keyed on
# the COMPOSITE {data_hash}_{regime}_{confidence_bucket} so a regime flip or
# a confidence move that crosses a 10pp bucket boundary regenerates the
# prose, while day-to-day posterior noise within a bucket stays a cache hit.
# Stored in the same `data_hash` VARCHAR column — no schema change. Bare-
# data_hash rows from earlier writes remain valid and are served as the
# fallback by get_endpoint_recommendation when no composite-key row exists.


def _confidence_bucket(confidence: float | None) -> int | None:
    """Round confidence (0..1) to the nearest 10 percentage points,
    round-half-up. Returns None when confidence is missing."""
    if confidence is None:
        return None
    try:
        pct = max(0.0, min(1.0, float(confidence))) * 100.0
    except (TypeError, ValueError):
        return None
    # +5 then integer-divide by 10 gives round-half-up (positives only).
    return int((pct + 5) // 10) * 10


def regime_cache_key(
    data_hash: str, regime: str | None, confidence: float | None,
) -> str:
    """Composite cache key for the recommendation prose:
    {data_hash}_{regime}_{bucket}. Falls back to the bare data_hash when
    regime or confidence is missing — the existing read path (latest by
    computed_at) still works for those rows, and a later warm with full
    regime/confidence info writes a proper composite-keyed row."""
    if not data_hash:
        return ""
    bucket = _confidence_bucket(confidence)
    if not regime or bucket is None:
        return data_hash
    return f"{data_hash}_{regime}_{bucket}"


def _parse_cache_key(key: str | None) -> tuple[str | None, str | None, int | None]:
    """Inverse of regime_cache_key. Bare-hash keys (no underscores in the
    SHA prefix) yield (hash, None, None). Composite keys yield all three.
    Robust to extra underscores in the regime token (rejoins the middle)."""
    if not key:
        return None, None, None
    parts = key.split("_")
    if len(parts) < 3:
        return key, None, None
    # bucket = last segment (digits); regime = everything between hash and bucket.
    try:
        bucket = int(parts[-1])
    except ValueError:
        return key, None, None
    return parts[0], "_".join(parts[1:-1]) or None, bucket


def _miss_reason(
    target_key: str, latest_key: str | None,
    data_hash: str, regime: str | None, confidence: float | None,
) -> str:
    """Classify a cache miss by comparing the requested composite key
    against the latest cached key. Used in the cio_recommendation_cache_miss
    log so the trigger is observable in production."""
    if not latest_key:
        return "no_cached_recommendation"
    latest_hash, latest_regime, latest_bucket = _parse_cache_key(latest_key)
    if latest_hash != data_hash:
        return "data_hash_change"
    if (latest_regime or None) != (regime or None):
        return "regime_shift"
    if latest_bucket != _confidence_bucket(confidence):
        return "confidence_shift"
    return "unknown"


# In-process guard: a flapping regime / bucket boundary near 85% should
# not fire a fresh LLM call on every endpoint read. The first miss schedules
# a regenerate; subsequent misses for the same composite key are no-ops
# until that task finishes.
_inflight_keys: set[str] = set()
# Hold strong references so a fire-and-forget task is not GC'd mid-run.
_bg_tasks: set = set()


async def _regenerate_under_key(key: str) -> None:
    """Run the full live-context + generation flow and persist under the
    supplied composite key. Fail-open. The inflight key is cleared in the
    finally block so a later miss can retry."""
    try:
        built = await _build_live_context()
        if built.get("error"):
            log.warning("cio_recommendation_regenerate_context_unavailable",
                        key=key, error=built["error"])
            return
        rec = generate_recommendation(built["context"], built["macro"])
        if rec.get("error"):
            log.warning("cio_recommendation_regenerate_generate_failed",
                        key=key, error=rec.get("error"))
            return
        await _persist(key, rec, built["context"].get("regime"))
        log.info("cio_recommendation_regenerated", key=key,
                 model=rec.get("_model"))
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_regenerate_failed",
                    key=key, error=str(exc))
    finally:
        _inflight_keys.discard(key)


def schedule_regime_aware_refresh(
    data_hash: str, regime: str | None, confidence: float | None, *,
    reason: str,
) -> None:
    """Schedule a background regenerate of the recommendation prose under
    the live regime-aware key. Logs the miss reason
    (regime_shift / confidence_shift / data_hash_change / unknown) so what
    triggered the regenerate is observable. No-op if a regenerate for the
    same key is already in flight."""
    key = regime_cache_key(data_hash, regime, confidence)
    if not key or key in _inflight_keys:
        return
    log.info(
        "cio_recommendation_cache_miss",
        reason=reason,
        data_hash=data_hash[:8] if data_hash else "",
        regime=regime,
        bucket=_confidence_bucket(confidence),
        key=key,
    )
    _inflight_keys.add(key)
    try:
        import asyncio
        task = asyncio.create_task(_regenerate_under_key(key))
        _bg_tasks.add(task)
        task.add_done_callback(_bg_tasks.discard)
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_regenerate_schedule_failed",
                    key=key, error=str(exc))
        _inflight_keys.discard(key)


async def get_endpoint_recommendation() -> dict | None:
    """Read path used by /api/v1/recommendation.

    Resolves the LIVE regime + confidence-bucket from detect_current_regime()
    and the current data_hash, then prefers a cached row stored under the
    composite key. On a cache miss, returns the most recent cached row
    (whatever its key) and schedules a background regenerate under the live
    key — so the tile stays fast and the next read serves the fresh prose.
    Fail-open to get_latest_recommendation() at every step."""
    try:
        import asyncio
        from tools.regime_detector import detect_current_regime
    except Exception:  # noqa: BLE001
        return await get_latest_recommendation()
    try:
        live = await asyncio.to_thread(detect_current_regime)
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_live_regime_unavailable",
                    error=str(exc))
        return await get_latest_recommendation()
    regime = (live or {}).get("hmm_regime")
    probs = (live or {}).get("hmm_probabilities") or {}
    confidence = probs.get(regime) if regime else None
    monthly_regime = (live or {}).get("monthly_hmm_regime")
    hmm_models_agree = (live or {}).get("hmm_models_agree", True)
    data_hash = await _current_data_hash()
    if not data_hash:
        return _attach_divergence(
            await get_latest_recommendation(),
            regime, confidence, monthly_regime, hmm_models_agree)
    target_key = regime_cache_key(data_hash, regime, confidence)
    # Try the composite-key cache (falls through to None on bare-hash keys
    # too, since the bare data_hash IS the composite when regime is None).
    rec = await get_cached_for_hash(target_key)
    if rec is not None:
        return _attach_divergence(
            rec, regime, confidence, monthly_regime, hmm_models_agree)
    latest = await get_latest_recommendation()
    # Schedule background regenerate (only when we have enough to compose
    # a real composite key — otherwise the legacy bare-hash row is correct
    # by definition).
    if regime and confidence is not None:
        reason = _miss_reason(
            target_key, (latest or {}).get("data_hash"),
            data_hash, regime, confidence)
        schedule_regime_aware_refresh(
            data_hash, regime, confidence, reason=reason)
    return _attach_divergence(
        latest, regime, confidence, monthly_regime, hmm_models_agree)


async def compute_implied_asset_allocation(
    blend_weights: dict[str, float] | None,
) -> dict[str, float] | None:
    """Translate the live regime-conditional blend (per-strategy weights)
    into asset-class percentages. The per-strategy avg_equity_weight /
    avg_bond_weight live in strategy_results_cache; we multiply each
    strategy's weight in the blend by its asset-class composition and
    sum to portfolio totals.

    Returns {equity_pct, bond_pct, cash_pct} as fractions of 1.0, OR
    None when the strategy cache is empty / the blend is missing /
    every blend weight is zero. Fail-open across the board: a cold
    cache returns None and the caller renders the existing CIO card
    without the new line.

    PURE READ: this helper does NOT recompute or refit anything. It
    pulls already-cached primitives only -- strategy_results_cache
    and the blend_weights dict the caller supplies (usually from the
    CIO recommendation's own blend_weights field, persisted at the
    last warm). Bridge #81.
    """
    if not blend_weights:
        return None
    try:
        from tools.cache import get_latest_strategy_cache
    except Exception as exc:  # noqa: BLE001
        log.warning("implied_asset_allocation_imports_failed",
                    error=str(exc))
        return None
    try:
        strategies = await get_latest_strategy_cache() or {}
    except Exception as exc:  # noqa: BLE001
        log.warning("implied_asset_allocation_cache_read_failed",
                    error=str(exc))
        return None
    if not strategies:
        return None

    total_eq = 0.0
    total_bd = 0.0
    total_ig = 0.0
    total_hy = 0.0
    # ig_hy_evidence_count -- number of contributing strategies that
    # carry the explicit IG/HY split fields (avg_ig_weight /
    # avg_hy_weight). When zero, no strategy in the live blend has
    # the new fields and we fall back to omitting ig_bond_pct /
    # hy_bond_pct from the result so the consumer falls through to
    # the combined-bonds rendering. When non-zero we surface the
    # split even if one or two strategies in the blend lack it
    # (treating absent as 0 IG / 0 HY for those rows -- they only
    # contribute via the combined bond_pct).
    ig_hy_evidence_count = 0
    total_w = 0.0
    for strategy, weight in blend_weights.items():
        try:
            w = float(weight or 0)
        except (TypeError, ValueError):
            continue
        if w <= 0:
            continue
        s = strategies.get(strategy) or {}
        try:
            eq = float(s.get("avg_equity_weight") or 0)
            bd = float(s.get("avg_bond_weight") or 0)
        except (TypeError, ValueError):
            continue
        ig_raw = s.get("avg_ig_weight")
        hy_raw = s.get("avg_hy_weight")
        if ig_raw is not None and hy_raw is not None:
            try:
                ig = float(ig_raw)
                hy = float(hy_raw)
                total_ig += w * ig
                total_hy += w * hy
                ig_hy_evidence_count += 1
            except (TypeError, ValueError):
                pass
        total_eq += w * eq
        total_bd += w * bd
        total_w += w

    if total_w <= 0:
        return None

    # Cash residual = whatever the strategies' weighted-average exposures
    # do not cover. A fully-invested blend (eq + bd ≈ 1) leaves cash ≈ 0;
    # a partial blend (cash drag from one of the strategies) surfaces
    # explicitly so the audience can SEE the un-invested fraction
    # instead of mentally subtracting.
    cash = max(0.0, 1.0 - total_eq - total_bd)
    result: dict[str, float] = {
        "equity_pct": round(total_eq, 4),
        "bond_pct": round(total_bd, 4),
        "cash_pct": round(cash, 4),
    }
    # IG/HY split (June 2026). Surfaced only when at least one strategy
    # in the live blend carries the new fields; otherwise the consumer
    # renders the combined-bonds row alone. Once the backfill script
    # has run AND the strategy cache holds the new keys on every row,
    # ig_hy_evidence_count == len(non-zero blend members) and the
    # detail rendering kicks in everywhere.
    if ig_hy_evidence_count > 0:
        result["ig_bond_pct"] = round(total_ig, 4)
        result["hy_bond_pct"] = round(total_hy, 4)
    return result


async def compute_regime_blends_implied(
    regime_blends: dict[str, dict[str, float]] | None,
    current_implied: dict[str, float] | None,
) -> dict[str, dict[str, Any]] | None:
    """For each regime in `regime_blends`, multiply its per-strategy
    weights by per-strategy avg_equity_weight / avg_bond_weight from
    strategy_results_cache and return the asset-class split + the
    delta (in percentage points) against `current_implied`.

    Returns:
        {
          "BULL": {
            "weights":  {strategy: weight},    # the input pass-through
            "equity_pct": 0.68, "bond_pct": 0.32, "cash_pct": 0.00,
            "equity_delta_pp": 35.6,           # percentage points
            "bond_delta_pp": -35.6,
          },
          "BEAR": {...},
          "TRANSITION": {...},
        }

    Fail-open: returns None on cold cache, empty regime_blends, or any
    internal error. Same pure-read contract as
    compute_implied_asset_allocation. Bridge (June 8 2026).
    """
    if not regime_blends:
        return None
    try:
        from tools.cache import get_latest_strategy_cache
    except Exception as exc:  # noqa: BLE001
        log.warning("regime_blends_implied_imports_failed", error=str(exc))
        return None
    try:
        strategies = await get_latest_strategy_cache() or {}
    except Exception as exc:  # noqa: BLE001
        log.warning("regime_blends_implied_cache_read_failed",
                    error=str(exc))
        return None
    if not strategies:
        return None

    cur_eq = (current_implied or {}).get("equity_pct")
    cur_bd = (current_implied or {}).get("bond_pct")
    cur_ig = (current_implied or {}).get("ig_bond_pct")
    cur_hy = (current_implied or {}).get("hy_bond_pct")
    out: dict[str, dict[str, Any]] = {}
    for regime, weights in regime_blends.items():
        if not isinstance(weights, dict) or not weights:
            continue
        total_eq = 0.0
        total_bd = 0.0
        total_ig = 0.0
        total_hy = 0.0
        ig_hy_evidence_count = 0
        total_w = 0.0
        for strategy, w_raw in weights.items():
            try:
                w = float(w_raw or 0)
            except (TypeError, ValueError):
                continue
            if w <= 0:
                continue
            s = strategies.get(strategy) or {}
            try:
                eq = float(s.get("avg_equity_weight") or 0)
                bd = float(s.get("avg_bond_weight") or 0)
            except (TypeError, ValueError):
                continue
            ig_raw = s.get("avg_ig_weight")
            hy_raw = s.get("avg_hy_weight")
            if ig_raw is not None and hy_raw is not None:
                try:
                    total_ig += w * float(ig_raw)
                    total_hy += w * float(hy_raw)
                    ig_hy_evidence_count += 1
                except (TypeError, ValueError):
                    pass
            total_eq += w * eq
            total_bd += w * bd
            total_w += w
        if total_w <= 0:
            continue
        cash = max(0.0, 1.0 - total_eq - total_bd)
        entry: dict[str, Any] = {
            "weights": dict(weights),
            "equity_pct": round(total_eq, 4),
            "bond_pct": round(total_bd, 4),
            "cash_pct": round(cash, 4),
        }
        # Delta in PERCENTAGE POINTS (not fractions). Surfaced for
        # every dimension whose current_implied has a value.
        if isinstance(cur_eq, (int, float)) and isinstance(cur_bd, (int, float)):
            entry["equity_delta_pp"] = round(
                (total_eq - float(cur_eq)) * 100, 1)
            entry["bond_delta_pp"] = round(
                (total_bd - float(cur_bd)) * 100, 1)
        # IG/HY split + delta (June 2026). Same evidence-count rule as
        # compute_implied_asset_allocation: only surface when at least
        # one contributing strategy carries the new fields.
        if ig_hy_evidence_count > 0:
            entry["ig_bond_pct"] = round(total_ig, 4)
            entry["hy_bond_pct"] = round(total_hy, 4)
            if isinstance(cur_ig, (int, float)) and isinstance(
                    cur_hy, (int, float)):
                entry["ig_bond_delta_pp"] = round(
                    (total_ig - float(cur_ig)) * 100, 1)
                entry["hy_bond_delta_pp"] = round(
                    (total_hy - float(cur_hy)) * 100, 1)
        out[regime] = entry
    return out or None


def compute_blend_change_trigger(
    regime: str | None,
    monthly_regime: str | None,
    hmm_models_agree: bool,
) -> str:
    """Synthesise the one-sentence "what would shift the blend" guidance
    that goes under the CIO card's allocation line.

    The CIO card asks: "what would cause us to rebalance?" The answer is
    "the regime read shifts" -- but expanding that into something the
    audience can act on means naming the watch points (the threshold
    constants from config.py) and any current divergence between the
    daily and monthly HMM fits.

    Single readable sentence, NOT a data dump. Fail-open: when the
    current regime is unknown the helper still returns a generic
    sentence so the card is never blank. Bridge #81.
    """
    from config import VIX_HIGH_THRESHOLD, BEAR_MARKET_THRESHOLD

    vix = int(VIX_HIGH_THRESHOLD)
    trend_pct = int(abs(BEAR_MARKET_THRESHOLD) * 100)

    if regime and not hmm_models_agree and monthly_regime:
        # The two HMMs already disagree -- the next blend shift is
        # whichever model concedes first. Lead with that.
        return (
            f"Daily HMM reads {regime} while the monthly HMM still reads "
            f"{monthly_regime}; the blend tilts further when the two "
            f"converge, or sooner if VIX sustains above {vix} or the "
            f"trailing equity trend falls below {-trend_pct}%."
        )
    if regime == "BEAR":
        return (
            f"Blend de-risks further on a deeper bear signal (VIX sustained "
            f"above {vix} or HY credit spreads widening), and re-risks "
            f"when the HMM flips back to BULL or TRANSITION."
        )
    if regime == "BULL":
        return (
            f"Blend stays risk-on while the HMM reads BULL; a regime flip "
            f"to BEAR or sustained VIX above {vix} would tilt the blend "
            f"toward MIN_VARIANCE and VOL_TARGETING."
        )
    if regime == "TRANSITION":
        return (
            f"Blend stays neutral while the HMM reads TRANSITION; a flip "
            f"to BULL re-risks toward growth strategies, and a flip to "
            f"BEAR tilts toward MIN_VARIANCE and VOL_TARGETING."
        )
    return (
        f"Blend shifts on the next HMM regime flip; the watch signals are "
        f"VIX above {vix}, a trailing equity trend below {-trend_pct}%, "
        f"or a sustained yield-curve inversion."
    )


def _attach_divergence(
    rec: dict | None,
    daily_regime: str | None,
    confidence: float | None,
    monthly_regime: str | None,
    hmm_models_agree: bool,
) -> dict | None:
    """Overlay divergence_disclosure on the recommendation dict when the
    daily HMM (live label) and the monthly HMM (blend weights) disagree.
    Live-state field, NOT baked into the cached prose — the disclosure
    reflects the moment of the read, not the moment the prose was written.
    Fail-open: if any input is missing, leave rec untouched."""
    if rec is None:
        return None
    if hmm_models_agree or not daily_regime or not monthly_regime:
        return rec
    pct = f"{float(confidence) * 100:.1f}%" if confidence is not None else "—"
    rec["divergence_disclosure"] = (
        f"Note: live regime signal ({daily_regime} at {pct}) diverges from "
        f"the blend regime ({monthly_regime}). Blend weights reflect the "
        f"monthly model; the live label reflects the daily model."
    )
    return rec


async def _persist(data_hash: str, rec: dict, regime: str | None) -> None:
    if not _DB_AVAILABLE or not data_hash:
        return
    import json

    from sqlalchemy import text
    try:
        async with AsyncSessionLocal() as session:  # type: ignore[union-attr]
            await session.execute(
                text(
                    "INSERT INTO cio_recommendations "
                    "(data_hash, signal, confidence, dissenting_view, "
                    " limitations, regime, model, raw_json) "
                    "VALUES (:h, :sig, CAST(:conf AS JSONB), :dis, "
                    " CAST(:lim AS JSONB), :reg, :model, "
                    " CAST(:raw AS JSONB)) "
                    "ON CONFLICT (data_hash) DO NOTHING"),
                {
                    "h": data_hash,
                    "sig": rec.get("signal"),
                    "conf": json.dumps(rec.get("confidence")),
                    "dis": rec.get("dissenting_view"),
                    "lim": json.dumps(rec.get("limitations")),
                    "reg": regime,
                    "model": rec.get("_model"),
                    "raw": json.dumps(rec),
                })
            await session.commit()
    except Exception as exc:  # noqa: BLE001
        log.warning("cio_recommendation_persist_error", error=str(exc))


async def _build_live_context() -> dict:
    """Render-side: assemble compute_context inputs from the live data —
    the strategy cache, a fresh HMM fit on the equity series, and the
    current regime read. Fail-open to {"error": ...}."""
    try:
        import pandas as pd
        from tools.cache import get_latest_strategy_cache, get_monthly_returns
        from tools.regime_detector import (
            detect_current_regime, fit_hmm_historical,
        )
    except Exception as exc:  # noqa: BLE001
        return {"error": f"imports_unavailable: {exc}"}

    strategy_results = await get_latest_strategy_cache()
    if not strategy_results:
        return {"error": "strategy_results_cache_empty"}
    monthly = await get_monthly_returns()
    if not monthly or not monthly.get("equity") or not monthly.get("dates"):
        return {"error": "monthly_equity_unavailable"}
    idx = pd.to_datetime(monthly["dates"])
    equity = pd.Series(monthly["equity"], index=idx).sort_index()
    hmm_result = fit_hmm_historical(equity)
    if not hmm_result or hmm_result.get("error"):
        return {"error": f"hmm_fit_failed: {(hmm_result or {}).get('error')}"}
    current = detect_current_regime()
    ctx = compute_context(strategy_results, hmm_result, current)
    if ctx.get("error"):
        return ctx
    macro = ""
    try:
        from tools.macro_context import get_macro_context
        macro = get_macro_context() or ""
    except Exception:  # noqa: BLE001
        macro = ""
    return {"context": ctx, "macro": macro}


async def refresh_cio_recommendation(*, force: bool = False) -> dict:
    """The hash-pipeline entry point. Builds the live context, composes the
    regime-aware cache key (data_hash + regime + confidence bucket), and
    serves the cached recommendation when that exact composite key already
    has a row. Otherwise fires the single LLM call and persists under the
    composite key. force=True recomputes even on a cache hit (operator
    backfill). Fail-open. _build_live_context is cheap (HMM fit + regime
    detect both use in-process caches), so always building first is a fair
    trade for picking up regime/bucket changes in the warm path."""
    data_hash = await _current_data_hash()
    built = await _build_live_context()
    if built.get("error"):
        log.warning("cio_recommendation_context_unavailable",
                    error=built["error"])
        return built
    regime = built["context"].get("regime")
    confidence = built["context"].get("probability")
    key = regime_cache_key(data_hash, regime, confidence)
    if not force:
        cached = await get_cached_for_hash(key)
        if cached:
            cached["cache"] = "hit"
            return cached
    rec = generate_recommendation(built["context"], built["macro"])
    if rec.get("error"):
        return rec
    await _persist(key, rec, regime)
    rec["cache"] = "miss"
    rec["data_hash"] = key
    log.info("cio_recommendation_computed",
             data_hash=data_hash[:8] if data_hash else "",
             regime=regime,
             bucket=_confidence_bucket(confidence),
             key=key,
             model=rec.get("_model"))
    return rec
