"""
tools/docx_generator.py

Helpers that assemble Word (.docx) deliverables from a dict of section
content. Used by the report endpoints in main.py — none of the routing
or LLM-call logic lives here. Keeping the document-construction code in
a single module means changing the AI DRAFT banner style, the page
margins, or the APA table format requires editing exactly one place.

Three deliverables share the same builder:
  - Midpoint paper (Sprint 6 Priority 1 — May 27 submission deadline)
  - Executive brief (Sprint 6 Priority 2)
  - Analytical appendix (Sprint 6 Priority 2)

The builder is unopinionated about which deliverable it's producing —
the caller supplies a title, list of section dicts, and an optional
strategy-results table. The mandatory AI DRAFT banner is added by the
builder so a caller can never accidentally ship without it.
"""
from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor


# CLAUDE.md Section 14 spec: amber background, dark text, bold uppercase,
# present on every page of every AI-generated document.
_AI_DRAFT_BANNER_TEXT = "AI DRAFT — REQUIRES HUMAN REVIEW"
_AI_DRAFT_SUBTITLE = (
    "This document was generated by an AI system using data from the "
    "Forest Capital Analytics Platform. All statistics, citations, and "
    "findings must be verified by a team member before submission. Do "
    "not submit without human review."
)


def _set_run_color(run, hex_color: str) -> None:
    """Apply a hex colour (e.g. '#f59e0b') to a run's font."""
    rgb = hex_color.lstrip("#")
    run.font.color.rgb = RGBColor(int(rgb[0:2], 16), int(rgb[2:4], 16), int(rgb[4:6], 16))


def _add_ai_draft_header(doc: Document) -> None:
    """
    Inserts the AI DRAFT banner into the document header so it appears on
    every page — meets the CLAUDE.md "footer/banner on every page" spec.

    The banner is rendered as two runs (heading + body) with amber colour
    on the heading. python-docx doesn't expose Word's shading XML in a
    convenient API, so we use bold amber text rather than a coloured
    background; visually distinctive enough and avoids fragile XML hacks.
    """
    section = doc.sections[0]
    header = section.header
    para = header.paragraphs[0]
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    heading_run = para.add_run(_AI_DRAFT_BANNER_TEXT)
    heading_run.bold = True
    heading_run.font.size = Pt(11)
    _set_run_color(heading_run, "#f59e0b")

    para.add_run("\n")
    body_run = para.add_run(_AI_DRAFT_SUBTITLE)
    body_run.italic = True
    body_run.font.size = Pt(8)
    _set_run_color(body_run, "#7a4a00")


def _add_title_block(doc: Document, title: str, subtitle: str | None) -> None:
    """Adds the title and optional subtitle as the first body paragraphs."""
    h = doc.add_heading(title, level=0)
    h.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if subtitle:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(subtitle)
        run.italic = True
        run.font.size = Pt(11)

    generated = doc.add_paragraph()
    generated.alignment = WD_ALIGN_PARAGRAPH.CENTER
    g_run = generated.add_run(
        f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
    )
    g_run.italic = True
    g_run.font.size = Pt(9)
    _set_run_color(g_run, "#64748b")


def _add_section(doc: Document, heading: str, body: str) -> None:
    """Adds an APA-style section: H1 heading followed by body paragraphs."""
    doc.add_heading(heading, level=1)
    # Split on blank lines so each paragraph in the source becomes a
    # paragraph in Word — matches Academic Writer's prose output.
    for para_text in body.strip().split("\n\n"):
        if not para_text.strip():
            continue
        doc.add_paragraph(para_text.strip())


def _add_strategy_table(doc: Document, strategy_results: dict[str, Any]) -> None:
    """
    Adds the canonical 10-row strategy comparison table in APA format.

    Columns: Strategy, CAGR, Sharpe, Max DD, p (FDR), CV Score, Tier 1.
    Sorted by Sharpe descending so the best strategies appear at the top —
    consistent with the dashboard ordering.
    """
    if not strategy_results:
        return

    doc.add_heading("Table 1: Strategy Comparison", level=2)
    note = doc.add_paragraph()
    note_run = note.add_run("Note. ")
    note_run.italic = True
    note.add_run(
        "All p-values reflect Benjamini-Hochberg FDR correction. "
        "Tier 1 gates passed (out of 5) indicate cumulative statistical robustness."
    )

    table = doc.add_table(rows=1, cols=7)
    table.style = "Light Grid Accent 1"
    header = table.rows[0].cells
    for i, label in enumerate(["Strategy", "CAGR", "Sharpe", "Max DD", "p (FDR)", "CV", "Gates"]):
        header[i].text = label
        # Bold the header row so it reads as a table header in Word.
        for run in header[i].paragraphs[0].runs:
            run.bold = True

    sorted_rows = sorted(
        strategy_results.items(),
        key=lambda kv: float(kv[1].get("sharpe_ratio", 0.0) or 0.0),
        reverse=True,
    )
    for name, r in sorted_rows:
        row = table.add_row().cells
        row[0].text = name.replace("_", " ")
        row[1].text = _fmt_pct(r.get("cagr"))
        row[2].text = _fmt_num(r.get("sharpe_ratio"))
        row[3].text = _fmt_pct(r.get("max_drawdown"))
        row[4].text = _fmt_p(r.get("p_value_corrected"))
        row[5].text = _fmt_num(r.get("cv_stability_score"))
        gates = r.get("tier1_gates_passed")
        row[6].text = f"{gates}/5" if gates is not None else "—"


def _fmt_pct(v: Any) -> str:
    if isinstance(v, (int, float)):
        return f"{v * 100:.2f}%"
    return "—"


def _fmt_num(v: Any) -> str:
    if isinstance(v, (int, float)):
        return f"{v:.3f}"
    return "—"


def _fmt_p(v: Any) -> str:
    if isinstance(v, (int, float)):
        return f"{v:.4f}" if v >= 0.001 else "< .001"
    return "—"


def build_docx(
    *,
    title: str,
    subtitle: str | None,
    sections: list[dict[str, str]],
    strategy_results: dict[str, Any] | None = None,
    references: list[str] | None = None,
) -> bytes:
    """
    Builds a .docx and returns the raw bytes ready for an HTTP response.

    Args:
        title:            Document title (rendered as H0 centred).
        subtitle:         Optional subtitle below the title.
        sections:         Ordered list of {"heading": str, "body": str}.
                          The body may contain blank-line-separated paragraphs;
                          each becomes a separate Word paragraph.
        strategy_results: When present, a Table 1 is inserted after the
                          Results section (or at the end if no Results section).
        references:       APA-formatted citation strings (one per line).
                          Rendered as a "References" section at the end.

    Returns:
        The .docx file as bytes — caller wraps in a StreamingResponse or
        writes to disk.
    """
    doc = Document()
    _add_ai_draft_header(doc)
    _add_title_block(doc, title, subtitle)

    inserted_table = False
    for sec in sections:
        heading = sec.get("heading", "Untitled Section")
        body = sec.get("body", "")
        _add_section(doc, heading, body)
        # Inject the strategy table immediately after the Results section
        # so the surrounding prose can reference "Table 1" naturally.
        if (
            strategy_results
            and not inserted_table
            and heading.lower().startswith("results")
        ):
            _add_strategy_table(doc, strategy_results)
            inserted_table = True

    # Catch-all: if no Results section was found but we have a table, append it
    # at the end so the data still appears.
    if strategy_results and not inserted_table:
        _add_strategy_table(doc, strategy_results)

    if references:
        doc.add_heading("References", level=1)
        for entry in references:
            doc.add_paragraph(entry)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
