"""
tools/html_report_generator.py

Builds a self-contained HTML deliverable from a list of section dicts.
Used by /api/reports/analytical-appendix — the Analytical Appendix is
35% of the grade and the grader needs a single openable file with no
external dependencies.

Why HTML rather than .docx for the appendix:
  The appendix renders the full data provenance registry, the entire
  strategy comparison table, all five sanity assertions, and the
  reference list — content that exceeds what Word's auto-numbering
  and table styles handle cleanly at scale. HTML gives us deterministic
  control over the layout, the document is one file (no docx zip
  internals to inspect), and the grader can View Source to audit
  exactly what was generated. The AI DRAFT banner is a sticky div
  rather than a Word header.

The builder is intentionally unopinionated about content. The caller
passes ordered sections + an optional strategy_results dict + an
optional provenance registry, and the builder assembles a single
HTML string. No JavaScript — print-friendly out of the box.
"""
from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import Any


_AI_DRAFT_BANNER_TEXT = "AI DRAFT — REQUIRES HUMAN REVIEW"
_AI_DRAFT_SUBTITLE = (
    "This document was generated by an AI system using data from the "
    "Forest Capital Analytics Platform. All statistics, citations, and "
    "findings must be verified by a team member before submission. Do "
    "not submit without human review."
)


def _escape(s: Any) -> str:
    """Coerces any value to a string and escapes HTML special chars."""
    return html.escape(str(s)) if s is not None else "—"


def _fmt_pct(v: Any, decimals: int = 2) -> str:
    if isinstance(v, (int, float)):
        return f"{v * 100:.{decimals}f}%"
    return "—"


def _fmt_num(v: Any, decimals: int = 3) -> str:
    if isinstance(v, (int, float)):
        return f"{v:.{decimals}f}"
    return "—"


def _fmt_p(v: Any) -> str:
    if isinstance(v, (int, float)):
        return f"{v:.4f}" if v >= 0.001 else "&lt; .001"
    return "—"


# CSS lives inline so the HTML file is self-contained. Print-friendly:
# AI DRAFT banner uses `position: fixed` only in screen mode and reverts
# to a regular top-of-page block when printing so it doesn't overlap
# every page. Strategy table uses tight metrics-font for readability.
_CSS = """
  :root {
    color-scheme: light;
    --banner: #f59e0b;
    --banner-text: #7a4a00;
    --border: #d4d4d8;
    --muted: #64748b;
    --accent: #1e40af;
  }
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                 Helvetica, Arial, sans-serif;
    color: #18181b;
    background: #fafafa;
    margin: 0;
    padding: 0;
    line-height: 1.6;
  }
  .ai-draft-banner {
    background: var(--banner);
    color: var(--banner-text);
    border-bottom: 2px solid #b45309;
    padding: 10px 24px;
    position: sticky;
    top: 0;
    z-index: 100;
    text-align: center;
  }
  .ai-draft-banner strong {
    text-transform: uppercase;
    letter-spacing: 0.1em;
    font-size: 13px;
    display: block;
  }
  .ai-draft-banner small {
    font-style: italic;
    color: #7a4a00;
    font-size: 11px;
    display: block;
    margin-top: 4px;
  }
  main {
    max-width: 800px;
    margin: 0 auto;
    padding: 32px 24px 64px;
    background: white;
    min-height: 100vh;
    box-shadow: 0 0 0 1px var(--border);
  }
  h1 { font-size: 26px; margin: 0 0 8px; }
  h2 {
    font-size: 18px;
    margin-top: 32px;
    padding-bottom: 6px;
    border-bottom: 1px solid var(--border);
    color: var(--accent);
  }
  h3 { font-size: 14px; margin-top: 20px; color: #27272a; }
  p { margin: 8px 0 12px; }
  .subtitle { color: var(--muted); font-style: italic; margin: 0 0 4px; }
  .generated { color: var(--muted); font-size: 11px; margin: 0 0 24px; }
  table {
    border-collapse: collapse;
    width: 100%;
    margin: 12px 0 18px;
    font-size: 12px;
  }
  th, td {
    border: 1px solid var(--border);
    padding: 6px 10px;
    text-align: left;
    vertical-align: top;
  }
  th {
    background: #f4f4f5;
    font-weight: 600;
    color: #27272a;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    font-size: 11px;
  }
  td.metric { font-family: "JetBrains Mono", Menlo, monospace; text-align: right; }
  td.pass { color: #166534; font-weight: 600; }
  td.fail { color: #991b1b; font-weight: 600; }
  td.warn { color: #92400e; font-weight: 600; }
  .table-caption {
    font-size: 12px;
    font-style: italic;
    color: var(--muted);
    margin-top: -6px;
    margin-bottom: 12px;
  }
  ul, ol { margin: 8px 0 14px; padding-left: 24px; }
  li { margin-bottom: 4px; }
  .ref-list {
    list-style: none;
    padding-left: 24px;
  }
  .ref-list li {
    text-indent: -24px;
    padding-left: 24px;
    margin-bottom: 10px;
  }
  @media print {
    body { background: white; }
    main { box-shadow: none; padding: 0 16px; }
    .ai-draft-banner {
      position: static;
      page-break-after: avoid;
    }
    h2 { page-break-after: avoid; }
    table { page-break-inside: avoid; }
  }
"""


def _render_strategy_table(strategy_results: dict[str, Any]) -> str:
    """
    Renders Table 1 — strategy comparison sorted by Sharpe descending.

    Same column set as the .docx generator so the appendix and the brief
    show identical numbers (a grader cross-referencing the two should
    never see disagreement).
    """
    if not strategy_results:
        return ""

    sorted_rows = sorted(
        strategy_results.items(),
        key=lambda kv: float(kv[1].get("sharpe_ratio", 0.0) or 0.0),
        reverse=True,
    )

    rows_html = []
    for name, r in sorted_rows:
        gates = r.get("tier1_gates_passed")
        gates_cell = f"{gates}/5" if gates is not None else "—"
        is_sig = bool(r.get("is_significant"))
        sig_cls = "pass" if is_sig else "warn" if (gates or 0) >= 3 else "fail"
        rows_html.append(
            "<tr>"
            f"<td>{_escape(name.replace('_', ' '))}</td>"
            f"<td class='metric'>{_fmt_pct(r.get('cagr'))}</td>"
            f"<td class='metric'>{_fmt_num(r.get('sharpe_ratio'))}</td>"
            f"<td class='metric'>{_fmt_pct(r.get('max_drawdown'))}</td>"
            f"<td class='metric'>{_fmt_p(r.get('p_value_corrected'))}</td>"
            f"<td class='metric'>{_fmt_num(r.get('cv_stability_score'))}</td>"
            f"<td class='metric {sig_cls}'>{gates_cell}</td>"
            "</tr>"
        )

    return (
        "<h3>Table 1 — Strategy comparison</h3>"
        "<table>"
        "<thead><tr>"
        "<th>Strategy</th><th>CAGR</th><th>Sharpe</th>"
        "<th>Max DD</th><th>p (FDR)</th><th>CV</th><th>Tier 1</th>"
        "</tr></thead>"
        f"<tbody>{''.join(rows_html)}</tbody>"
        "</table>"
        "<p class='table-caption'>"
        "Note. All p-values reflect Benjamini-Hochberg FDR correction "
        "across the ten-strategy universe. Tier 1 gates (out of 5) "
        "indicate cumulative statistical robustness."
        "</p>"
    )


def _render_provenance_table(registry: list[dict[str, Any]] | None) -> str:
    """Renders the data series registry as an APA-style provenance table."""
    if not registry:
        return ""
    rows_html = []
    for s in registry:
        rows_html.append(
            "<tr>"
            f"<td>{_escape(s.get('series_id'))}</td>"
            f"<td>{_escape(s.get('display_name'))}</td>"
            f"<td>{_escape(s.get('source_type'))}</td>"
            f"<td>{_escape(s.get('frequency'))}</td>"
            f"<td class='metric'>{_escape(s.get('row_count'))}</td>"
            "</tr>"
        )
    return (
        "<h3>Table 2 — Data provenance registry</h3>"
        "<table>"
        "<thead><tr>"
        "<th>Series ID</th><th>Display name</th><th>Source type</th>"
        "<th>Frequency</th><th>Rows</th>"
        "</tr></thead>"
        f"<tbody>{''.join(rows_html)}</tbody>"
        "</table>"
        "<p class='table-caption'>"
        "Note. Every value in this study traces to exactly one row of "
        "this registry. Excel-provided series are authoritative; "
        "external fetches (yfinance, FRED, Ken French) are used only "
        "where the Excel file does not provide coverage. See cross-"
        "validation results below for equity reconciliation."
        "</p>"
    )


def _render_section(heading: str, body: str) -> str:
    """Wraps a heading and prose body in HTML. Pre-escapes the body so the
    Academic Writer's plain-text output renders correctly even when the
    prose contains < or > characters."""
    paragraphs = []
    for p in body.strip().split("\n\n"):
        p = p.strip()
        if not p:
            continue
        paragraphs.append(f"<p>{_escape(p)}</p>")
    return f"<h2>{_escape(heading)}</h2>\n" + "\n".join(paragraphs)


def build_html_report(
    *,
    title: str,
    subtitle: str | None,
    sections: list[dict[str, str]],
    strategy_results: dict[str, Any] | None = None,
    provenance_registry: list[dict[str, Any]] | None = None,
    references: list[str] | None = None,
) -> str:
    """
    Builds a single self-contained HTML string.

    Strategy table is inserted after the section whose heading begins
    with "Statistical Results" or "Results" so prose can reference
    "Table 1" naturally. Provenance table is inserted after "Data Sources".

    Args:
        title:               Document title.
        subtitle:            Optional subtitle below the title.
        sections:            Ordered [{heading, body}] list.
        strategy_results:    Optional — when provided, injects Table 1.
        provenance_registry: Optional — when provided, injects Table 2.
        references:          Optional APA reference strings (one per line).
    """
    section_html_parts: list[str] = []
    table_inserted = False
    provenance_inserted = False

    for sec in sections:
        heading = sec.get("heading", "Untitled Section")
        body = sec.get("body", "")
        section_html_parts.append(_render_section(heading, body))

        # Insert Table 1 after the Results section.
        if (
            strategy_results
            and not table_inserted
            and (heading.lower().startswith("statistical results")
                 or heading.lower().startswith("results"))
        ):
            section_html_parts.append(_render_strategy_table(strategy_results))
            table_inserted = True

        # Insert Table 2 after the Data Sources section.
        if (
            provenance_registry
            and not provenance_inserted
            and heading.lower().startswith("data sources")
        ):
            section_html_parts.append(_render_provenance_table(provenance_registry))
            provenance_inserted = True

    # Catch-all: append tables at end if their host sections weren't named.
    if strategy_results and not table_inserted:
        section_html_parts.append(_render_strategy_table(strategy_results))
    if provenance_registry and not provenance_inserted:
        section_html_parts.append(_render_provenance_table(provenance_registry))

    if references:
        refs_html = "".join(f"<li>{_escape(r)}</li>" for r in references)
        section_html_parts.append(
            f"<h2>References</h2><ul class='ref-list'>{refs_html}</ul>"
        )

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    subtitle_html = (
        f"<p class='subtitle'>{_escape(subtitle)}</p>" if subtitle else ""
    )

    return (
        "<!DOCTYPE html>\n"
        "<html lang='en'>\n<head>\n"
        "<meta charset='utf-8'>\n"
        f"<title>{_escape(title)}</title>\n"
        f"<style>{_CSS}</style>\n"
        "</head>\n<body>\n"
        "<div class='ai-draft-banner'>"
        f"<strong>{_AI_DRAFT_BANNER_TEXT}</strong>"
        f"<small>{_AI_DRAFT_SUBTITLE}</small>"
        "</div>\n"
        "<main>\n"
        f"<h1>{_escape(title)}</h1>\n"
        f"{subtitle_html}\n"
        f"<p class='generated'>Generated {generated_at}</p>\n"
        + "\n".join(section_html_parts)
        + "\n</main>\n</body>\n</html>"
    )
