"""
tools/script_generation.py

Builds a presentation_script editor draft from a presentation_deck
draft plus academic context (the executive brief and midpoint paper).

The script is generated by the Academic Writer through the
generator-evaluator harness — a document generation, not a
conversational reply, so the harness (not a bare call_claude) is used,
the same pattern as the midpoint paper. The generated markdown blob is
parsed into a TipTap document: '## ' headings → H2, '**Speaker: …**'
→ H3, '*Transition: …*' → blockquote, everything else → paragraphs.

Fail-open: in the test environment, or on any generation failure, a
deterministic fallback script is assembled from the deck — every
slide's real title and speaker label with a [DATA PENDING] delivery
paragraph — so the endpoint always produces a complete, parseable
draft covering every slide.
"""
from __future__ import annotations

import re
from typing import Any

import structlog

from config import ENVIRONMENT

log = structlog.get_logger(__name__)

# The delivery-time basis — 150 words per minute (CLAUDE.md / Commit C).
WORDS_PER_MINUTE = 150

_SYSTEM_PROMPT = (
    "You are writing a presentation script for a Forest Capital "
    "quantitative investment strategy pitch to faculty and investors at "
    "Queens University Charlotte, McColl School of Business, FNA 670 "
    "practicum. The presentation is 16 slides, approximately 20-25 "
    "minutes total. Multiple speakers are presenting."
)

_DATA_PENDING = "[DATA PENDING]"


def _slide_text(slide: dict[str, Any]) -> str:
    """The body text of a canvas slide — every text element joined."""
    els = slide.get("elements") or []
    return "\n".join(
        str(e.get("content") or "") for e in els
        if isinstance(e, dict) and e.get("type") == "text").strip()


def deck_speakers(slides: list[dict[str, Any]]) -> list[str]:
    """Unique speaker names across the deck, in first-seen order."""
    out: list[str] = []
    for s in slides:
        if not isinstance(s, dict):
            continue
        sp = str(s.get("speaker") or "").strip()
        if sp and sp not in out:
            out.append(sp)
    return out


def build_script_prompt(
    slides: list[dict[str, Any]],
    exec_brief_text: str | None,
    midpoint_text: str | None,
) -> str:
    """The user prompt — the output-structure spec, the academic context,
    and the per-slide content the script must expand on."""
    slide_blocks: list[str] = []
    for i, s in enumerate(slides, start=1):
        title = str(s.get("title") or f"Slide {i}")
        speaker = str(s.get("speaker") or "").strip() or "Unassigned"
        notes = str(s.get("speaker_notes") or "").strip()
        slide_blocks.append(
            f"Slide {i}: {title}\n"
            f"Speaker: {speaker}\n"
            f"Content: {_slide_text(s) or '(no slide text)'}\n"
            f"Speaker notes: {notes or '(none)'}")

    return (
        "Generate a complete presentation script with the following "
        "structure:\n\n"
        "OPENING\n"
        "[2-3 sentences of scene-setting context. No speaker label.]\n\n"
        "Then for each slide in order:\n\n"
        "## Slide {n}: {title}\n"
        "**Speaker: {speaker name or 'Unassigned' if null}**\n\n"
        "{3-4 paragraphs of spoken delivery text that:\n"
        "- Expands on the slide content and data points\n"
        "- References specific figures and findings from the slide\n"
        "- Connects to the investment thesis and academic argument\n"
        "- Flows naturally from the previous slide\n"
        "- Uses clear language suitable for a mixed faculty/investor "
        "audience}\n\n"
        "*Transition: {one sentence bridging to the next slide}*\n\n"
        "(Omit the transition after the final slide)\n\n"
        "CLOSING\n"
        "[2-3 sentences closing the presentation]\n\n"
        "Academic context (executive brief):\n"
        f"{(exec_brief_text or '').strip() or 'Not available'}\n\n"
        "Additional context (midpoint paper):\n"
        f"{(midpoint_text or '').strip() or 'Not available'}\n\n"
        "Slide content:\n" + "\n\n".join(slide_blocks)
    )


def _fallback_script(slides: list[dict[str, Any]]) -> str:
    """A deterministic script blob in the generated format — real slide
    headers and speaker labels, [DATA PENDING] delivery prose. Used in
    the test environment and when generation fails."""
    parts = [
        "OPENING",
        f"{_DATA_PENDING} — the opening narrative is generated at runtime.",
    ]
    n = len(slides)
    for i, s in enumerate(slides, start=1):
        title = str(s.get("title") or f"Slide {i}")
        speaker = str(s.get("speaker") or "").strip() or "Unassigned"
        parts.append(f"## Slide {i}: {title}")
        parts.append(f"**Speaker: {speaker}**")
        parts.append(
            f"{_DATA_PENDING} — the delivery narrative for this slide is "
            "generated at runtime.")
        if i < n:
            parts.append(f"*Transition: {_DATA_PENDING}*")
    parts.append("CLOSING")
    parts.append(f"{_DATA_PENDING} — the closing narrative is generated "
                 "at runtime.")
    return "\n\n".join(parts)


_HEADING_RE = re.compile(r"^#{1,3}\s+(.+?)\s*$")
_SPEAKER_RE = re.compile(r"^\*\*\s*(Speaker:.+?)\s*\*\*$", re.IGNORECASE)
_TRANSITION_RE = re.compile(r"^\*\s*(Transition:.+?)\s*\*$", re.IGNORECASE)


def _text_node(text: str) -> dict[str, Any]:
    return {"type": "text", "text": text}


def script_to_tiptap(raw: str) -> tuple[dict[str, Any], str]:
    """Parses a generated script blob into (content_json, content_text).

    Blocks are separated by blank lines and classified: a '## …' heading
    (or a bare OPENING / CLOSING line) → H2, '**Speaker: …**' → H3,
    '*Transition: …*' → blockquote, anything else → a paragraph."""
    nodes: list[dict[str, Any]] = []
    text_lines: list[str] = []
    for block in re.split(r"\n\s*\n", raw or ""):
        block = block.strip()
        if not block:
            continue
        single = " ".join(line.strip() for line in block.splitlines())

        heading = _HEADING_RE.match(block.splitlines()[0]) \
            if block.startswith("#") else None
        speaker = _SPEAKER_RE.match(single)
        transition = _TRANSITION_RE.match(single)

        if heading:
            label = heading.group(1).strip()
            nodes.append({"type": "heading", "attrs": {"level": 2},
                          "content": [_text_node(label)]})
            text_lines.append(label)
        elif single.upper() in ("OPENING", "CLOSING"):
            nodes.append({"type": "heading", "attrs": {"level": 2},
                          "content": [_text_node(single.upper().title())]})
            text_lines.append(single.upper().title())
        elif speaker:
            label = speaker.group(1).strip()
            nodes.append({"type": "heading", "attrs": {"level": 3},
                          "content": [_text_node(label)]})
            text_lines.append(label)
        elif transition:
            label = transition.group(1).strip()
            nodes.append({"type": "blockquote", "content": [
                {"type": "paragraph", "content": [_text_node(label)]}]})
            text_lines.append(label)
        else:
            nodes.append({"type": "paragraph",
                          "content": [_text_node(single)]})
            text_lines.append(single)

    content_json = {"type": "doc", "content": nodes}
    return content_json, "\n\n".join(text_lines).strip()


def _slide_section_count(raw: str) -> int:
    """How many '## Slide …' headers a generated blob carries."""
    return len(re.findall(r"^#{1,3}\s+Slide\b", raw or "", re.MULTILINE))


def _run_harness(
    slides: list[dict[str, Any]],
    exec_brief_text: str | None,
    midpoint_text: str | None,
) -> str:
    """Generates the script through the Academic Writer + harness."""
    from agents.base import SONNET_MODEL, call_claude
    from agents.evaluator_prompts import presentation_script_evaluator_prompt
    from agents.harness import GeneratorEvaluatorHarness

    user_prompt = build_script_prompt(slides, exec_brief_text, midpoint_text)
    harness = GeneratorEvaluatorHarness()
    result = harness.run(
        generator_fn=lambda prompt: call_claude(
            SONNET_MODEL, _SYSTEM_PROMPT, prompt, max_tokens=6000,
            trigger="script_generation"),
        evaluator_prompt=presentation_script_evaluator_prompt(),
        generator_prompt=user_prompt,
        context=user_prompt,
        agent_id="presentation_script",
    )
    return result.response


def generate_script(
    deck_draft: dict[str, Any],
    exec_brief: dict[str, Any] | None,
    midpoint: dict[str, Any] | None,
    *,
    substitution_table: dict[str, str] | None = None,
) -> dict[str, Any]:
    """
    Builds the presentation-script content from a deck draft and the
    optional academic-context drafts. Returns content_json (TipTap),
    content_text, and the word / speaker / slide counts.

    June 28 2026 (Phase 2 substitution-deferral) -- when
    substitution_table is supplied AND DEFER_SUBSTITUTION_TO_EXPORT
    is on, content_json preserves any {{TOKEN}} placeholders the
    LLM emitted + content_text is derived from the substituted
    projection (full-text search + word counts see resolved
    values). When substitution_table is None or empty, both
    columns share the raw text -- legacy behaviour.

    The deck slides feeding the script's prompt already carry
    resolved values (deck_to_editor substitutes at its boundary
    regardless of flag, per the Phase 2 audit), so the
    LLM-emitted script naturally references resolved values
    rather than tokens. The substitution_table here is a
    safety net for any {{TOKEN}} that survives in narrative
    LLM output (the system prompt does not currently teach
    placeholders, so this typically produces 0 substitutions
    -- content_text == raw -- but the architecture is in
    place for a future prompt update).
    """
    content = deck_draft.get("content_json") or {}
    slides = content.get("slides", []) if isinstance(content, dict) else []
    exec_text = (exec_brief or {}).get("content_text") if exec_brief else None
    midpoint_text = (midpoint or {}).get("content_text") if midpoint else None

    raw = ""
    if ENVIRONMENT != "test" and slides:
        try:
            raw = _run_harness(slides, exec_text, midpoint_text)
        except Exception as exc:  # noqa: BLE001 — fall back to a complete draft
            log.warning("script_generation_failed", error=str(exc))
            raw = ""

    # Fall back when generation is unavailable or did not cover every
    # slide — the draft must always be complete and parseable.
    if not raw or _slide_section_count(raw) < len(slides):
        raw = _fallback_script(slides)

    # June 28 2026 -- soft-fail hard-lock for the script.
    # Mirrors harness_narrative's wrap-and-persist behaviour
    # for brief / appendix: scan raw for untoken-backed
    # numerics; when violations remain, wrap each with
    # <unverified>...</unverified> tags so the editor +
    # document audit can flag them for human review.
    # Operator directive (June 28 2026): document-type
    # agnostic -- script gets the same soft-fail treatment.
    # Fail-open: any scanner error leaves raw unchanged.
    if substitution_table:
        try:
            from tools.untoken_numeric_check import (
                find_untoken_backed_numerics,
                wrap_unverified,
            )
            _script_viols = find_untoken_backed_numerics(
                raw, substitution_table)
            if _script_viols:
                log.warning(
                    "script_untoken_lock_soft_fail",
                    remaining_violations=len(_script_viols),
                    sample_offenders=[
                        v.raw_value
                        for v in _script_viols[:10]],
                    note=(
                        "hard-lock detected raw numerics in "
                        "script output; wrapping with "
                        "<unverified> tags for human review."))
                raw = wrap_unverified(raw, _script_viols)
        except Exception as exc:  # noqa: BLE001
            log.warning(
                "script_untoken_lock_check_failed",
                error=str(exc))

    # June 28 2026 -- parallel substituted projection for
    # content_text under deferred substitution.
    content_json, content_text = script_to_tiptap(raw)
    if substitution_table:
        try:
            from tools.numeric_substitution import (
                apply_substitutions,
            )
            substituted_raw, _ = apply_substitutions(
                raw, substitution_table)
            _, content_text_substituted = script_to_tiptap(
                substituted_raw)
            content_text = content_text_substituted
        except Exception as exc:  # noqa: BLE001
            log.warning(
                "script_substitution_deferral_failed",
                error=str(exc))

    return {
        "content_json": content_json,
        "content_text": content_text,
        "word_count": len(content_text.split()),
        "speaker_count": len(deck_speakers(slides)),
        "slide_count": len(slides),
    }
