"""mcp_bridge.config — env-driven configuration with sensible defaults.

A single source of truth so the server, worker, and CLI all read the
same values. Configuration order (highest priority first):
  1. Environment variables
  2. ~/.config/mcp-bridge/config.json (created by `bridge init`)
  3. Hardcoded defaults

The ONE flag that materially changes behaviour is `worker_enabled`.
Default False — manual fetch is the safe default (Michael's live
Claude Code session is the consumer, full context, no autonomous
execution). Setting it True via env (`MCP_BRIDGE_WORKER_ENABLED=1`)
or config file lets the worker daemon take over hands-off.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# The config file the `bridge init` command writes. JSON because it
# is human-editable and the values are simple scalars.
_CONFIG_PATH = Path.home() / ".config" / "mcp-bridge" / "config.json"


def _env_bool(name: str, default: bool = False) -> bool:
    """Parse a boolean env var. Accepts '1', 'true', 'yes', 'on'
    case-insensitively as True; everything else as False."""
    v = os.getenv(name)
    if v is None:
        return default
    return v.strip().lower() in ("1", "true", "yes", "on")


def _env_int(name: str, default: int) -> int:
    v = os.getenv(name)
    if v is None or v.strip() == "":
        return default
    try:
        return int(v)
    except ValueError:
        return default


@dataclass
class BridgeConfig:
    """The complete configuration surface. Every field has a default
    so the bridge runs without a config file."""

    # ── Network ────────────────────────────────────────────────────────
    host: str = "127.0.0.1"
    port: int = 8765

    # ── Auth ───────────────────────────────────────────────────────────
    # Bearer token required on every MCP request. Generated by
    # `bridge init` if not supplied via env. An empty token means
    # "no auth" — fine for localhost-only deploys but unsafe the
    # moment the bridge is exposed via a tunnel.
    auth_token: str = ""

    # ── Storage ────────────────────────────────────────────────────────
    db_path: str = str(Path.home() / ".local" / "share" /
                        "mcp-bridge" / "queue.db")

    # ── Worker ─────────────────────────────────────────────────────────
    # OFF by default per the May 23 2026 spec. When False the bridge
    # ships and runs but no autonomous execution happens — the user's
    # live Claude Code session pulls via the /check-mobile slash
    # command. Flip to True to enable hands-off execution.
    worker_enabled: bool = False

    # How often the worker polls the queue (seconds). Keep tight —
    # 2 seconds feels instant on mobile and is well under any
    # reasonable tunnel timeout.
    worker_poll_interval_s: float = 2.0

    # Per-prompt timeout (seconds) the worker enforces on the
    # `claude -p` subprocess. A prompt that runs longer than this
    # gets killed and the queue row marked failed with a timeout
    # message. 10 minutes is generous for the most expensive
    # Forest Capital prompts.
    worker_prompt_timeout_s: int = 600

    # Path to the claude CLI binary. Default `claude` (PATH lookup).
    # Override when the binary lives outside PATH.
    claude_binary: str = "claude"

    # Optional persistent session ID — the worker passes this to
    # `claude -p --resume <session_id>` so context survives across
    # queued prompts. Empty string means fresh session per prompt.
    worker_session_id: str = ""

    # Extra arguments fed to every `claude -p` invocation. JSON-
    # encodable list. Use this for things like
    # --output-format json (already added by the worker), --model,
    # or --dangerously-skip-permissions if Michael wants the
    # autonomous worker to run without prompts.
    claude_extra_args: list[str] = field(default_factory=list)

    # ── Behavior ───────────────────────────────────────────────────────
    # Maximum prompt length (bytes) accepted by push_prompt. Above
    # this, the server rejects with 422. Guards against runaway
    # payloads. 64 KB is plenty — most prompts are <2 KB.
    max_prompt_bytes: int = 64 * 1024


def load_config() -> BridgeConfig:
    """Resolve the merged config: env > file > defaults."""
    cfg = BridgeConfig()

    # ── File overlay ────────────────────────────────────────────────────
    if _CONFIG_PATH.exists():
        try:
            data = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            data = {}
        for k, v in (data or {}).items():
            if hasattr(cfg, k):
                setattr(cfg, k, v)

    # ── Env overlay (highest precedence) ────────────────────────────────
    if os.getenv("MCP_BRIDGE_HOST"):
        cfg.host = os.environ["MCP_BRIDGE_HOST"]
    cfg.port = _env_int("MCP_BRIDGE_PORT", cfg.port)
    if os.getenv("MCP_BRIDGE_AUTH_TOKEN") is not None:
        cfg.auth_token = os.environ["MCP_BRIDGE_AUTH_TOKEN"]
    if os.getenv("MCP_BRIDGE_DB_PATH"):
        cfg.db_path = os.environ["MCP_BRIDGE_DB_PATH"]
    if os.getenv("MCP_BRIDGE_WORKER_ENABLED") is not None:
        cfg.worker_enabled = _env_bool("MCP_BRIDGE_WORKER_ENABLED")
    cfg.worker_poll_interval_s = float(_env_int(
        "MCP_BRIDGE_POLL_INTERVAL_S",
        int(cfg.worker_poll_interval_s)))
    cfg.worker_prompt_timeout_s = _env_int(
        "MCP_BRIDGE_PROMPT_TIMEOUT_S", cfg.worker_prompt_timeout_s)
    if os.getenv("MCP_BRIDGE_CLAUDE_BINARY"):
        cfg.claude_binary = os.environ["MCP_BRIDGE_CLAUDE_BINARY"]
    if os.getenv("MCP_BRIDGE_SESSION_ID") is not None:
        cfg.worker_session_id = os.environ["MCP_BRIDGE_SESSION_ID"]
    cfg.max_prompt_bytes = _env_int(
        "MCP_BRIDGE_MAX_PROMPT_BYTES", cfg.max_prompt_bytes)

    return cfg


def write_default_config(token: str, extra: dict[str, Any] | None = None
                          ) -> Path:
    """Writes a fresh config file at the standard location. Used by
    `bridge init`. Existing config is overwritten (use git if you
    care about the previous values). Returns the path written."""
    _CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    data: dict[str, Any] = {"auth_token": token}
    if extra:
        data.update(extra)
    _CONFIG_PATH.write_text(
        json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")
    return _CONFIG_PATH


def config_path() -> Path:
    """Where the config file lives. Exposed so the CLI can print it
    after `bridge init`."""
    return _CONFIG_PATH
